Repository angular/angular, pull requests merged in 2018-10, with the labels that each got.

#26260 Update to rules_typescript 0.20.1 and rules_nodejs 0.15.0
  .circleci/config.yml
  integration/bazel/package.json
  integration/bazel/yarn.lock
  package.json
  packages/bazel/package.bzl
  packages/bazel/rules_nodejs_package.bzl
  packages/bazel/rules_typescript_package.bzl
  packages/bazel/src/ng_setup_workspace.bzl
  tools/npm/package.json
  tools/npm/yarn.lock
  yarn.lock
Labels: cla: yes

#26279 Update to rules_typescript 0.20.2
  integration/bazel/package.json
  integration/bazel/yarn.lock
  package.json
  packages/bazel/package.bzl
  packages/bazel/rules_typescript_package.bzl
  packages/bazel/src/ng_setup_workspace.bzl
  tools/npm/package.json
  tools/npm/yarn.lock
  yarn.lock
Labels: cla: yes

#26432 6.1.x build upgrade jasminewd2 types
  aio/package.json
  aio/tools/examples/shared/package.json
  aio/tools/examples/shared/yarn.lock
  aio/yarn.lock
  integration/cli-hello-world/package.json
  integration/cli-hello-world/yarn.lock
  modules/types.d.ts
  package.json
  packages/examples/tsconfig-build.json
  packages/examples/tsconfig.json
  tools/types-ext/jasminewd2.d.ts
  yarn.lock
Labels: PR action: merge, PR target: patch-only, cla: yes, comp: build & ci

#26465 build: update ngcontainer to bazel 0.18.0
  .bazelignore
  .bazelrc
  .circleci/config.yml
  .gitignore
  .pullapprove.yml
  WORKSPACE
  docs/BAZEL.md
  packages/bazel/package.bzl
  packages/core/BUILD.bazel
  tools/ngcontainer/Dockerfile
  tools/ngcontainer/README.md
Labels: cla: yes

#26879 fix(core): Remove static dependency from @angular/core to @angular/compiler (#26734)
  packages/compiler-cli/src/ngtsc/annotations/src/component.ts
  packages/compiler-cli/src/ngtsc/annotations/src/directive.ts
  packages/compiler-cli/src/ngtsc/typecheck/src/type_check_block.ts
  packages/compiler/package.json
  packages/compiler/src/compiler.ts
  packages/compiler/src/compiler_facade_interface.ts
  packages/compiler/src/jit_compiler_facade.ts
  packages/compiler/src/render3/r3_module_compiler.ts
  packages/compiler/src/render3/view/api.ts
  packages/compiler/src/render3/view/compiler.ts
  packages/compiler/src/render3/view/t2_api.ts
  packages/compiler/src/render3/view/util.ts
  packages/compiler/src/util.ts
  packages/compiler/test/compiler_facade_interface_spec.ts
  packages/core/BUILD.bazel
  packages/core/package.json
  packages/core/src/render3/di.ts
  packages/core/src/render3/jit/compiler_facade.ts
  packages/core/src/render3/jit/compiler_facade_interface.ts
  packages/core/src/render3/jit/directive.ts
  packages/core/src/render3/jit/injectable.ts
  packages/core/src/render3/jit/module.ts
  packages/core/src/render3/jit/pipe.ts
  packages/core/src/render3/jit/util.ts
  packages/core/test/bundling/animation_world/bundle.golden_symbols.json
  packages/core/test/bundling/hello_world/BUILD.bazel
  packages/core/test/bundling/hello_world/bundle.golden_symbols.json
  packages/core/test/bundling/hello_world/treeshaking_spec.ts
  packages/core/test/bundling/hello_world_r2/BUILD.bazel
  packages/core/test/bundling/hello_world_r2/bundle.golden_symbols.json
  packages/core/test/bundling/hello_world_r2/treeshaking_spec.ts
  packages/core/test/bundling/injection/BUILD.bazel
  packages/core/test/bundling/injection/bundle.golden_symbols.json
  packages/core/test/bundling/injection/treeshaking_spec.ts
  packages/core/test/bundling/todo/BUILD.bazel
  packages/core/test/bundling/todo/bundle.golden_symbols.json
  packages/core/test/bundling/todo/todo_e2e_spec.ts
  packages/core/test/bundling/todo_r2/BUILD.bazel
  packages/core/test/bundling/todo_r2/bundle.golden_symbols.json
  packages/core/test/bundling/todo_r2/todo_e2e_spec.ts
  packages/core/test/render3/BUILD.bazel
  packages/core/test/render3/compiler_canonical/back_patch_types_specs.ts
  packages/core/test/render3/compiler_canonical/patch_types_spec.ts
  packages/core/test/render3/compiler_canonical/small_app_spec.ts
  packages/core/test/render3/ivy/jit_spec.ts
  packages/core/test/render3/load_domino.ts
  tools/npm/yarn.lock
  tools/testing/BUILD.bazel
  tools/testing/init_browser_spec.ts
  tools/testing/init_node_spec.ts
Labels: PR action: merge, PR target: patch-only, cla: yes
