Repository angular/angular, pull requests merged in 2019-03, with the labels that each got.

#29030 build(compiler-cli): upgrade chokidar to latest version
  package.json
  packages/compiler-cli/package.json
  yarn.lock
Labels: PR action: merge, PR action: merge-assistance, PR target: LTS-only, cla: yes, comp: build & ci

#29381 revert: refactor(ivy): Update query-related comments (#29342)
  packages/core/src/linker/query_list.ts
  packages/core/src/render3/query.ts
  packages/core/test/render3/query_spec.ts
  tools/public_api_guard/core/core.d.ts
Labels: cla: yes

#29549 Add schematics config doc to v7
  aio/content/guide/workspace-config.md
Labels: PR target: patch-only, aio: preview, cla: yes, comp: docs, docsarea: cli and config

#29552 build: add version name pre release check [patch]
  .bazelrc
  docs/BAZEL.md
  scripts/release/pre-check
  tools/bazel_stamp_vars.js
  tools/bazel_stamp_vars.sh
Labels: PR action: merge, PR target: patch-only, cla: yes, comp: build & ci

#29558 Revert "feat(ivy): add property instruction (#29513)"
  packages/core/src/render3/instructions/instructions.ts
  packages/core/src/render3/state.ts
  packages/core/test/render3/instructions_spec.ts
Labels: PR target: master-only, cla: yes
