Repository angular/angular, pull requests merged in 2020-01, with the labels that each got.

#34717 refactor(ivy): delete `ɵɵelementHostAttrs` instruction
  integration/_payload-limits.json
  packages/core/src/render3/component.ts
  packages/core/src/render3/instructions/element.ts
  packages/core/src/render3/instructions/lview_debug.ts
  packages/core/src/render3/instructions/shared.ts
  packages/core/src/render3/interfaces/node.ts
  packages/core/src/render3/node_selector_matcher.ts
  packages/core/src/render3/state.ts
  packages/core/src/render3/styling/class_differ.ts
  packages/core/src/render3/util/attrs_utils.ts
  packages/core/test/acceptance/host_binding_spec.ts
  packages/core/test/bundling/cyclic_import/bundle.golden_symbols.json
  packages/core/test/bundling/hello_world/bundle.golden_symbols.json
  packages/core/test/bundling/todo/bundle.golden_symbols.json
  packages/core/test/render3/node_selector_matcher_spec.ts
Labels: PR target: master & patch, cla: yes, comp: ivy

#34967 build: update `firebase-tools` to the latest version
  aio/package.json
  aio/yarn.lock
  package.json
  yarn.lock
Labels: PR action: merge, PR action: merge-assistance, PR target: patch-only, cla: yes, comp: build & ci, comp: docs-infra

#35006 ci(docs-infra): ignore node version in `aio_monitoring_stable` CI job
  aio/scripts/test-production.sh
Labels: PR action: merge, PR target: LTS-only, cla: yes, comp: build & ci, comp: docs-infra, type: bug/fix
