Repository angular/angular, pull requests merged in 2021-01, with the labels that each got.

#40328 Bump version to "v11.0.6" with changelog.
  CHANGELOG.md
  package.json
Labels: PullApprove: disable, action: merge, cla: yes, comp: build & ci

#40329 docs: release notes for the v11.0.6 release
  CHANGELOG.md
Labels: PullApprove: disable, action: merge, cla: yes, comp: build & ci

#40330 Bump version to "v11.1.0-next.4" with changelog.
  CHANGELOG.md
  package.json
Labels: PullApprove: disable, action: merge, cla: yes, comp: build & ci

#40343 Bump version to "v11.0.7" with changelog.
  CHANGELOG.md
  package.json
Labels: cla: yes

#40345 docs: release notes for the v11.0.7 release
  CHANGELOG.md
Labels: cla: yes

#40391 Bump version to "v11.0.8" with changelog.
  CHANGELOG.md
  package.json
Labels: PullApprove: disable, action: merge, cla: yes, target: patch

#40392 docs: release notes for the v11.0.8 release
  CHANGELOG.md
Labels: cla: yes

#40414 Bump version to "v11.0.9" with changelog.
  CHANGELOG.md
  package.json
Labels: cla: yes

#40415 docs: release notes for the v11.0.9 release
  CHANGELOG.md
Labels: cla: yes

#40417 Bump version to "v11.1.0-next.5" with changelog.
  CHANGELOG.md
  package.json
Labels: cla: yes

#40418 Update next branch to reflect new release-train "v11.2.0-next.0".
  CHANGELOG.md
  package.json
Labels: cla: yes

#40420 Bump version to "v11.1.0-rc.0" with changelog.
  CHANGELOG.md
  package.json
Labels: cla: yes

#40421 docs: cherry-pick changelog from the 11.1.0-rc.0 release
  CHANGELOG.md
Labels: cla: yes

#40598 Bump version to "v11.1.1" with changelog.
  CHANGELOG.md
  package.json
Labels: PullApprove: disable, action: merge, cla: yes, comp: build & ci

#40599 docs: release notes for the v11.1.1 release
  CHANGELOG.md
Labels: PullApprove: disable, action: merge, cla: yes, comp: build & ci

#40600 Bump version to "v11.2.0-next.0" with changelog.
  CHANGELOG.md
Labels: PullApprove: disable, action: merge, cla: yes, comp: build & ci

#40604 release: bump the version to 12.0.0-next.0
  package.json
Labels: PullApprove: disable, action: merge, cla: yes, comp: build & ci, target: major
