Repository angular/angular, pull requests merged in 2021-02, with the labels that each got.

#40793 Bump version to "v12.0.0-next.0" with changelog.
  CHANGELOG.md
Labels: PullApprove: disable, action: merge, cla: yes, comp: build & ci, target: major

#40887 Bump version to "v11.2.1" with changelog.
  CHANGELOG.md
  package.json
Labels: PullApprove: disable, action: merge, cla: yes, comp: build & ci

#40888 docs: release notes for the v11.2.1 release
  CHANGELOG.md
Labels: PullApprove: disable, action: merge, cla: yes, comp: build & ci, target: major

#40889 Bump version to "v12.0.0-next.1" with changelog.
  CHANGELOG.md
  package.json
Labels: PullApprove: disable, action: merge, cla: yes, comp: build & ci, target: major

#40951 Bump version to "v11.2.2" with changelog.
  CHANGELOG.md
  package.json
Labels: PullApprove: disable, action: merge, cla: yes, comp: build & ci, target: patch

#40981 Bump version to "v11.2.3" with changelog.
  CHANGELOG.md
  package.json
Labels: PullApprove: disable, action: merge, cla: yes, comp: build & ci

#40982 docs: copy release notes from 11.2.3
  CHANGELOG.md
Labels: cla: yes, target: major

#40983 Bump version to "v12.0.0-next.2" with changelog.
  CHANGELOG.md
  package.json
Labels: PullApprove: disable, action: merge, cla: yes, comp: build & ci
