Repository angular/angular, pull requests merged in 2021-06, with the labels that each got.

#42456 fix(dev-infra): github oauth token not picked up by Octokit
  dev-infra/ng-dev.js
  dev-infra/utils/git/github.ts
Labels: action: merge, cla: yes, comp: dev-infra, target: minor

#42458 fix(dev-infra): update outdated build-worker.js file
  dev-infra/build-worker.js
Labels: action: merge, cla: yes, comp: dev-infra, target: minor

#42531 Bump version to "v12.0.4" with changelog.
  CHANGELOG.md
  package.json
Labels: PullApprove: disable, action: merge, cla: yes, comp: build & ci

#42721 Bump version to "v12.1.1" with changelog.
  CHANGELOG.md
  package.json
Labels: PullApprove: disable, action: merge, cla: yes, comp: build & ci, target: patch

#42722 docs: release notes for the v12.1.1 release
  CHANGELOG.md
Labels: PullApprove: disable, action: merge, cla: yes, comp: build & ci

#42723 Bump version to "v12.2.0-next.1" with changelog.
  CHANGELOG.md
  package.json
Labels: PullApprove: disable, action: merge, cla: yes, comp: build & ci
