Repository angular/angular, pull requests merged in 2022-12, with the labels that each got.

#48391 Bump version to "v15.0.3" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, PullApprove: disable

#48392 docs: release notes for the v15.0.3 release
  CHANGELOG.md
Labels: action: merge, area: build & ci, PullApprove: disable

#48393 Bump version to "v15.1.0-next.2" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, PullApprove: disable

#48491 Bump version to "v15.0.4" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, PullApprove: disable

#48493 docs: release notes for the v15.0.4 release
  CHANGELOG.md
Labels: action: merge, area: docs, PullApprove: disable

#48496 Bump version to "v15.1.0-next.3" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, PullApprove: disable
