Repository angular/angular, pull requests merged in 2022-03, with the labels that each got.

#45241 Bump version to "v13.2.5" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, comp: build & ci, PullApprove: disable

#45242 docs: release notes for the v13.2.5 release
  CHANGELOG.md
Labels: action: merge, comp: build & ci, PullApprove: disable

#45243 Bump version to "v14.0.0-next.5" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, comp: build & ci, PullApprove: disable

#45299 Bump version to "v13.2.6" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, comp: build & ci, PullApprove: disable

#45300 docs: release notes for the v13.2.6 release
  CHANGELOG.md
Labels: action: merge, comp: build & ci, PullApprove: disable

#45301 Bump version to "v14.0.0-next.6" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, comp: build & ci, PullApprove: disable

#45319 Set up 13.3.0 release for TypeScript 4.6 support
  integration/typings_test_ts46/BUILD.bazel
  integration/typings_test_ts46/include-all.ts
  integration/typings_test_ts46/package.json
  integration/typings_test_ts46/tsconfig.json
  package.json
  packages/bazel/package.json
  packages/compiler-cli/package.json
  packages/compiler-cli/src/typescript_support.ts
  packages/compiler-cli/test/downlevel_decorators_transform_spec.ts
  packages/service-worker/worker/testing/clients.ts
  packages/zone.js/package.json
  packages/zone.js/test/typings/package.json
  packages/zone.js/yarn.lock
  yarn.lock
Labels: action: review

#45321 Bump version to "v13.3.0-rc.0" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, comp: build & ci, PullApprove: disable

#45322 docs: release notes for the v13.3.0-rc.0 release
  CHANGELOG.md
Labels: action: merge, comp: build & ci, PullApprove: disable

#45363 Bump version to "v13.2.7" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, comp: build & ci, PullApprove: disable

#45366 docs: release notes for the v13.3.0 release
  CHANGELOG.md
Labels: action: merge, comp: build & ci, PullApprove: disable

#45368 Bump version to "v14.0.0-next.7" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, comp: build & ci, PullApprove: disable

#45422 fix(docs-infra): prevent framing of AIO with X-Frame-Options
  aio/firebase.json
Labels: action: merge, comp: docs-infra, target: rc

#45423 fix(docs-infra): prevent framing of AIO with X-Frame-Options
  aio/firebase.json
Labels: action: merge, comp: docs-infra, target: rc
