Repository angular/angular, pull requests merged in 2022-11, with the labels that each got.

#47962 Bump version to "v14.2.9" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, area: build & ci, PullApprove: disable

#47963 docs: release notes for the v14.2.9 release
  CHANGELOG.md
Labels: action: merge, area: docs, area: build & ci, PullApprove: disable

#47967 Bump version to "v15.0.0-rc.2" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, area: build & ci, PullApprove: disable

#47968 docs: release notes for the v15.0.0-rc.2 release
  CHANGELOG.md
Labels: action: merge, area: docs, area: build & ci, PullApprove: disable

#48012 Bump version to "v14.2.10" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, area: build & ci, PullApprove: disable

#48013 docs: release notes for the v14.2.10 release
  CHANGELOG.md
Labels: action: merge, area: build & ci, PullApprove: disable

#48014 Bump version to "v15.0.0-rc.3" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, area: build & ci, PullApprove: disable

#48015 docs: release notes for the v15.0.0-rc.3 release
  CHANGELOG.md
Labels: action: merge, area: docs, area: build & ci, PullApprove: disable

#48054 Bump version to "v15.0.0-rc.4" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, area: build & ci, PullApprove: disable

#48086 docs: release notes for the v14.2.11 release
  CHANGELOG.md
Labels: action: merge, area: docs, area: build & ci, target: minor, PullApprove: disable

#48087 Bump version to "v15.0.0" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, area: build & ci, PullApprove: disable

#48088 docs: release notes for the v15.0.0 release
  CHANGELOG.md
Labels: action: merge, area: docs, area: build & ci, PullApprove: disable

#48154 Bump version to "v14.2.12" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, area: build & ci, PullApprove: disable

#48155 docs: release notes for the v14.2.12 release
  CHANGELOG.md
Labels: action: merge, area: docs, area: build & ci, PullApprove: disable

#48158 Bump version to "v13.3.12" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, area: build & ci, PullApprove: disable

#48159 docs: release notes for the v13.3.12 release
  CHANGELOG.md
Labels: action: merge, area: build & ci, PullApprove: disable

#48189 Bump version to "v15.1.0-next.0" with changelog.
  CHANGELOG.md
Labels: action: merge, area: build & ci, PullApprove: disable

#48191 docs: release notes for the v15.0.1 release
  CHANGELOG.md
Labels: action: merge, area: build & ci, PullApprove: disable

#48262 build(bazel): fix aio deploy script
  aio/scripts/deploy-to-firebase/index.mjs
  aio/scripts/deploy-to-firebase/pre-deploy-actions.mjs
  aio/scripts/deploy-to-firebase/pre-deploy-actions.spec.mjs
Labels: action: merge, target: patch

#48304 Bump version to "v15.0.2" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, area: build & ci, PullApprove: disable

#48305 docs: release notes for the v15.0.2 release
  CHANGELOG.md
Labels: action: merge, area: docs, area: build & ci, PullApprove: disable

#48306 Bump version to "v15.1.0-next.1" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, area: build & ci, PullApprove: disable
