Repository angular/angular, pull requests merged in 2022-09, with the labels that each got.

#47371 Bump version to "v14.2.1" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, comp: build & ci, PullApprove: disable

#47372 docs: release notes for the v14.2.1 release
  CHANGELOG.md
Labels: action: merge, comp: build & ci, PullApprove: disable

#47373 Bump version to "v15.0.0-next.1" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, comp: build & ci, PullApprove: disable

#47319 build(bazel): run firebase deployment tests under bazel
  aio/package.json
  aio/scripts/deploy-to-firebase/BUILD.bazel
  aio/scripts/deploy-to-firebase/index.mjs
  aio/scripts/deploy-to-firebase/index.spec.mjs
Labels: comp: build & ci

#47363 build(bazel): fix a bug where aio firebase utils tests could not link deps
  aio/tests/deployment/unit/BUILD.bazel
  aio/tests/deployment/unit/test.js
  aio/tools/firebase-test-utils/BUILD.bazel
  aio/tools/firebase-test-utils/FirebaseRedirectSource.spec.ts
  aio/tools/firebase-test-utils/test.js
Labels: comp: build & ci

#47375 build(bazel): fix load statement to point to new dev-infra package
  integration/index.bzl
Labels: comp: build & ci

#47442 Bump version to "v14.2.2" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, comp: build & ci, target: patch, PullApprove: disable

#47444 docs: release notes for the v14.2.2 release
  CHANGELOG.md
Labels: action: merge, comp: docs, comp: build & ci, target: minor, PullApprove: disable

#47445 Bump version to "v15.0.0-next.2" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, comp: build & ci, target: minor, PullApprove: disable

#47509 Bump version to "v14.2.3" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, comp: build & ci, PullApprove: disable

#47510 docs: release notes for the v14.2.3 release
  CHANGELOG.md
Labels: action: merge, comp: docs, comp: build & ci, PullApprove: disable

#47511 Bump version to "v15.0.0-next.3" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, comp: build & ci, PullApprove: disable

#47414 build(bazel): update documentation for docs authors
  aio/BUILD.bazel
  aio/README.md
  aio/aio_targets.bzl
  aio/package.json
  aio/scripts/fast-serve-and-watch.js
  aio/tools/README.md
  aio/tools/example-zipper/README.md
  aio/tools/examples/README.md
  aio/tools/stackblitz-builder/README.md
  aio/tools/transforms/authors-package/base-authoring-package.js
  aio/yarn.lock
Labels: comp: docs, comp: build & ci

#47572 Bump version to "v14.2.4" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, comp: build & ci, PullApprove: disable

#47573 docs: release notes for the v14.2.4 release
  CHANGELOG.md
Labels: action: merge, comp: build & ci, PullApprove: disable

#47574 Bump version to "v15.0.0-next.4" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, comp: build & ci, PullApprove: disable
