Repository angular/angular, pull requests merged in 2022-10, with the labels that each got.

#47527 build(bazel): clean up pathing in aio build tooling
  WORKSPACE
  aio/BUILD.bazel
  aio/content/examples/examples.bzl
  aio/scripts/run-with-local-server.mjs
  aio/tools/examples/BUILD.bazel
  aio/tools/examples/constants.js
  aio/tools/examples/create-example.js
  aio/tools/examples/example-boilerplate.js
  aio/tools/examples/example-boilerplate.spec.js
  aio/tools/transforms/config.js
  tools/bazel-repo-patches/rules_nodejs__b02128b178.patch
  tools/esm-loader/esm-loader.mjs
Labels: action: cleanup, comp: build & ci, comp: docs-infra, target: patch

#47638 Bump version to "v14.2.5" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, comp: build & ci, PullApprove: disable

#47639 docs: release notes for the v14.2.5 release
  CHANGELOG.md
Labels: action: merge, comp: build & ci, PullApprove: disable

#47640 Bump version to "v15.0.0-next.5" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, comp: build & ci, PullApprove: disable

#47749 build: update to the latest version of the feature triage action
  .github/workflows/feature-requests.yml
Labels: action: merge, comp: build & ci, target: patch

#47752 docs: release notes for the v14.2.6 release
  CHANGELOG.md
Labels: action: merge, comp: docs, comp: build & ci, PullApprove: disable

#47755 Bump version to "v15.0.0-next.6" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, area: build & ci, PullApprove: disable

#47759 build: update commit message based labels action
  .github/workflows/dev-infra.yml
Labels: action: merge, area: build & ci, target: patch

#47815 Bump version to "v14.2.7" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, area: build & ci, PullApprove: disable

#47816 docs: release notes for the v14.2.7 release
  CHANGELOG.md
Labels: action: merge, area: docs, area: build & ci, PullApprove: disable

#47817 Bump version to "v15.0.0-rc.0" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, area: build & ci, PullApprove: disable

#47818 docs: release notes for the v15.0.0-rc.0 release
  CHANGELOG.md
Labels: action: merge, area: docs, area: build & ci, PullApprove: disable

#47806 build(bazel): list docs entrypoints under packages to simplify docgen target
  packages.bzl
  packages/BUILD.bazel
Labels: action: merge, area: bazel

#47588 build(bazel): create AIO example playgrounds for manual testing
  .bazelignore
  aio/.gitignore
  aio/README.md
  aio/content/examples/examples.bzl
  aio/package.json
  aio/tools/examples/BUILD.bazel
  aio/tools/examples/README.md
  aio/tools/examples/create-example-playground-wrapper.mjs
  aio/tools/examples/create-example-playground.mjs
  aio/tools/examples/example-sandbox.mjs
  aio/tools/examples/run-example-e2e.mjs
  packages/animations/BUILD.bazel
  packages/bazel/BUILD.bazel
  packages/common/BUILD.bazel
  packages/compiler-cli/BUILD.bazel
  packages/compiler/BUILD.bazel
  packages/core/BUILD.bazel
  packages/elements/BUILD.bazel
  packages/forms/BUILD.bazel
  packages/language-service/BUILD.bazel
  packages/platform-browser-dynamic/BUILD.bazel
  packages/platform-browser/BUILD.bazel
  packages/platform-server/BUILD.bazel
  packages/router/BUILD.bazel
  packages/service-worker/BUILD.bazel
  packages/upgrade/BUILD.bazel
Labels: action: merge, area: bazel

#47617 build(bazel): use workspace status command for AIO version stamping
  aio/BUILD.bazel
  aio/package.json
  aio/scripts/deploy-to-firebase/BUILD.bazel
  aio/src/app/navigation/navigation.model.ts
  aio/src/app/navigation/navigation.service.spec.ts
  aio/tools/transforms/angular-base-package/index.js
  aio/tools/transforms/angular-base-package/services/bazelStampedProperties.js
  aio/tools/transforms/angular.io-package/processors/processNavigationMap.js
Labels: action: merge, action: cleanup, area: build & ci, target: patch

#47792 build(bazel): fix a bug where local ngc couldn't be linked into AIO example tests
  aio/tools/examples/example-sandbox.mjs
Labels: action: merge, area: dev-infra

#47826 build(bazel): support ibazel for AIO example playgrounds
  aio/README.md
  aio/tools/examples/BUILD.bazel
  aio/tools/examples/create-example-playground-wrapper.mjs
  aio/tools/examples/create-example-playground.mjs
  aio/tools/examples/example-sandbox.mjs
Labels: action: merge, action: cleanup, area: dev-infra

#47878 Bump version to "v14.2.8" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, area: build & ci, PullApprove: disable

#47879 docs: release notes for the v14.2.8 release
  CHANGELOG.md
Labels: action: merge, area: docs, area: build & ci, PullApprove: disable

#47881 docs: release notes for the v15.0.0-rc.1 release
  CHANGELOG.md
Labels: action: merge, area: docs, area: build & ci, PullApprove: disable
