Repository angular/angular, pull requests merged in 2022-05, with the labels that each got.

#45864 refactor(common): drop the `loader` input in favor of `IMAGE_LOADER` token
  packages/common/src/directives/ng_optimized_image.ts
  packages/common/test/directives/ng_optimized_image_spec.ts
Labels: comp: common, PullApprove: disable, target: feature

#45879 release: bump the next branch to v14.1.0-next.0
  package.json
Labels: action: merge, comp: build & ci, target: major

#45806 build(bazel): create targets for aio docs tests
  BUILD.bazel
  aio/BUILD.bazel
  aio/content/examples/BUILD.bazel
  aio/package.json
  aio/tools/example-zipper/BUILD.bazel
  aio/tools/example-zipper/exampleZipper.mjs
  aio/tools/stackblitz-builder/BUILD.bazel
  aio/tools/stackblitz-builder/builder.mjs
  aio/tools/transforms/BUILD.bazel
  aio/tools/transforms/angular-api-package/BUILD.bazel
  aio/tools/transforms/angular-base-package/BUILD.bazel
  aio/tools/transforms/angular-content-package/BUILD.bazel
  aio/tools/transforms/angular-errors-package/BUILD.bazel
  aio/tools/transforms/angular-extended-diagnostics-package/BUILD.bazel
  aio/tools/transforms/angular.io-package/BUILD.bazel
  aio/tools/transforms/authors-package/BUILD.bazel
  aio/tools/transforms/cli-docs-package/BUILD.bazel
  aio/tools/transforms/cli-docs-package/index.js
  aio/tools/transforms/config.js
  aio/tools/transforms/content-package/BUILD.bazel
  aio/tools/transforms/examples-package/BUILD.bazel
  aio/tools/transforms/examples-package/services/region-parser.js
  aio/tools/transforms/helpers/BUILD.bazel
  aio/tools/transforms/links-package/BUILD.bazel
  aio/tools/transforms/remark-package/BUILD.bazel
  aio/tools/transforms/target-package/BUILD.bazel
  aio/tools/transforms/templates/BUILD.bazel
  aio/tools/transforms/test.js
  aio/yarn.lock
Labels: comp: docs-infra

#45938 refactor(common): rename `NgOptimizedImage` directive selector
  packages/common/src/directives/ng_optimized_image.ts
  packages/common/test/directives/ng_optimized_image_spec.ts
  packages/core/test/bundling/image-directive/index.ts
Labels: comp: common, PullApprove: disable, target: feature

#45757 feat(common): Add image lazy loading and fetchpriority
  packages/common/src/directives/ng_optimized_image.ts
  packages/common/test/directives/ng_optimized_image_spec.ts
Labels: comp: common, PullApprove: disable, target: feature

#45940 fix(common): detect `data:` and `blob:` inputs in `NgOptimizedImage` directive
  packages/common/src/directives/ng_optimized_image.ts
  packages/common/test/directives/ng_optimized_image_spec.ts
Labels: comp: common, PullApprove: disable, target: feature

#45924 refactor(common): mark experimental `NgOptimizedImage` directive as standalone
  packages/common/src/directives/ng_optimized_image.ts
  packages/common/src/private_export.ts
  packages/common/test/directives/ng_optimized_image_spec.ts
  packages/core/test/bundling/image-directive/index.ts
Labels: action: review, comp: common, PullApprove: disable, target: feature

#45957 docs: release notes for the v13.3.7 release
  CHANGELOG.md
Labels: action: merge, comp: build & ci, PullApprove: disable

#45958 Bump version to "v14.0.0-rc.0" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, comp: build & ci, PullApprove: disable

#45959 docs: release notes for the v14.0.0-rc.0 release
  CHANGELOG.md
Labels: action: merge, comp: build & ci, PullApprove: disable

#45950 refactor(common): move `NgOptimizedImage` logic that sets `src` to a different hook
  packages/common/src/directives/ng_optimized_image.ts
Labels: comp: common, PullApprove: disable, target: feature

#45964 test(common): configure e2e testing infrastructure for `NgOptimizedImage` test app
  packages/core/test/bundling/image-directive/BUILD.bazel
  packages/core/test/bundling/image-directive/basic/basic.e2e-spec.ts
  packages/core/test/bundling/image-directive/basic/basic.ts
  packages/core/test/bundling/image-directive/index.html
  packages/core/test/bundling/image-directive/index.ts
  packages/core/test/bundling/image-directive/start-server.js
  packages/core/test/bundling/image-directive/tsconfig-e2e.json
Labels: comp: common, PullApprove: disable, target: feature

#45976 Bump version to "v13.3.8" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, comp: build & ci, PullApprove: disable

#45977 docs: release notes for the v13.3.8 release
  CHANGELOG.md
Labels: action: merge, comp: build & ci, PullApprove: disable

#45984 perf(common): monitor LCP only for images without `priority` attribute
  packages/common/src/directives/ng_optimized_image.ts
Labels: comp: common, PullApprove: disable, target: feature

#46014 test(common): fix relative URL issue in web tests
  packages/common/test/directives/ng_optimized_image_spec.ts
Labels: comp: common, PullApprove: disable, target: feature

#46015 test(common): reorg e2e folders for the `NgOptimizedImage` directive tests
  packages/core/test/bundling/image-directive/BUILD.bazel
  packages/core/test/bundling/image-directive/e2e/a.png
  packages/core/test/bundling/image-directive/e2e/b.png
  packages/core/test/bundling/image-directive/e2e/basic/basic.e2e-spec.ts
  packages/core/test/bundling/image-directive/e2e/basic/basic.ts
  packages/core/test/bundling/image-directive/e2e/lcp-check/lcp-check.e2e-spec.ts
  packages/core/test/bundling/image-directive/e2e/lcp-check/lcp-check.ts
  packages/core/test/bundling/image-directive/e2e/start-server.js
  packages/core/test/bundling/image-directive/e2e/tsconfig-e2e.json
  packages/core/test/bundling/image-directive/e2e/util.ts
  packages/core/test/bundling/image-directive/index.ts
  packages/core/test/bundling/image-directive/playground.ts
Labels: comp: common, PullApprove: disable, target: feature

#46042 Bump version to "v13.3.9" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, comp: build & ci, PullApprove: disable

#46043 docs: release notes for the v13.3.9 release
  CHANGELOG.md
Labels: action: merge, comp: build & ci, PullApprove: disable

#46044 Bump version to "v14.0.0-rc.1" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, comp: build & ci, PullApprove: disable

#46045 docs: release notes for the v14.0.0-rc.1 release
  CHANGELOG.md
Labels: action: merge, comp: build & ci, PullApprove: disable

#46072 ci: temporarily publish snapshots for `image-directive` branch
  .circleci/config.yml
Labels: action: merge, target: feature

#46116 refactor(common): create an NgModule for the `NgOptimizedImage` directive
  packages/common/src/directives/ng_optimized_image.ts
  packages/common/src/private_export.ts
  packages/common/test/directives/ng_optimized_image_spec.ts
  packages/core/test/bundling/image-directive/e2e/basic/basic.ts
  packages/core/test/bundling/image-directive/e2e/lcp-check/lcp-check.ts
  packages/core/test/bundling/image-directive/playground.ts
Labels: comp: common, PullApprove: disable, target: feature

#45903 build(bazel): create targets for aio example tooling tests
  WORKSPACE
  aio/tools/examples/BUILD.bazel
  aio/tools/examples/constants.js
  aio/tools/examples/create-example.spec.js
  aio/tools/examples/example-boilerplate.js
  aio/tools/examples/example-boilerplate.spec.js
  aio/tools/examples/shared/package.json
  aio/tools/examples/test.js
Labels: comp: build & ci

#45952 build(bazel): run aio application e2e tests under bazel
  WORKSPACE
  aio/BUILD.bazel
  aio/package.json
  aio/tests/e2e/protractor.conf.js
  aio/yarn.lock
Labels: comp: build & ci

#46130 test(common): backport `NgOptimizedImage` to 13.3.x for testing purposes
  .circleci/config.yml
  goldens/public-api/common/errors.md
  packages/common/src/directives/ng_optimized_image.ts
  packages/common/src/errors.ts
  packages/common/src/private_export.ts
  packages/common/test/directives/ng_optimized_image_spec.ts
  packages/core/src/core_private_export.ts
Labels: comp: common, PullApprove: disable, target: feature

#46111 feat(common): support loading attribute for NgOptimizedImage
  packages/common/src/directives/ng_optimized_image.ts
  packages/common/test/directives/ng_optimized_image_spec.ts
Labels: comp: common, PullApprove: disable, target: feature

#46183 test: update error codes used in the `NgOptimizedImage` tests
  packages/common/test/directives/ng_optimized_image_spec.ts
Labels: comp: common, PullApprove: disable, target: feature

#46203 Bump version to "v13.3.11" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, comp: build & ci, PullApprove: disable

#46204 docs: release notes for the v13.3.11 release
  CHANGELOG.md
Labels: action: merge, comp: build & ci, PullApprove: disable

#46205 Bump version to "v14.0.0-rc.3" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, comp: build & ci, PullApprove: disable

#46206 docs: release notes for the v14.0.0-rc.3 release
  CHANGELOG.md
Labels: action: merge, comp: build & ci, PullApprove: disable
