Repository angular/angular, pull requests merged in 2022-08, with the labels that each got.

#47028 Bump version to "v14.1.1" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, comp: build & ci, PullApprove: disable

#47029 docs: release notes for the v14.1.1 release
  CHANGELOG.md
Labels: action: merge, comp: build & ci, PullApprove: disable

#47030 Bump version to "v14.2.0-next.0" with changelog.
  CHANGELOG.md
Labels: action: merge, comp: build & ci, PullApprove: disable

#47013 feat(common): define public API surface for NgOptimizedImage directive
  goldens/public-api/common/index.md
  packages/common/src/common.ts
  packages/common/src/directives/ng_optimized_image/image_loaders/cloudflare_loader.ts
  packages/common/src/directives/ng_optimized_image/image_loaders/cloudinary_loader.ts
  packages/common/src/directives/ng_optimized_image/image_loaders/image_loader.ts
  packages/common/src/directives/ng_optimized_image/image_loaders/imagekit_loader.ts
  packages/common/src/directives/ng_optimized_image/image_loaders/imgix_loader.ts
  packages/common/src/directives/ng_optimized_image/index.ts
  packages/common/src/directives/ng_optimized_image/ng_optimized_image.ts
  packages/common/src/directives/ng_optimized_image/preconnect_link_checker.ts
Labels: comp: common, PullApprove: disable, target: feature

#47045 docs: add description and usage notes to the NgOptimizedImage directive
  packages/common/src/directives/ng_optimized_image/ng_optimized_image.ts
  packages/common/src/private_export.ts
  packages/core/test/bundling/image-directive/e2e/basic/basic.ts
  packages/core/test/bundling/image-directive/e2e/image-distortion/image-distortion.ts
  packages/core/test/bundling/image-directive/e2e/lcp-check/lcp-check.ts
  packages/core/test/bundling/image-directive/e2e/preconnect-check/preconnect-check.ts
  packages/core/test/bundling/image-directive/playground.ts
Labels: comp: common, PullApprove: disable, target: feature

#46733 build(bazel): incrementally run aio example e2e tests
  BUILD.bazel
  WORKSPACE
  aio/content/examples/angular-compiler-options/example-config.json
  aio/content/examples/examples.bzl
  aio/content/examples/forms-overview/example-config.json
  aio/content/examples/http/example-config.json
  aio/content/examples/i18n/example-config.json
  aio/content/examples/ngcontainer/BUILD.bazel
  aio/content/examples/schematics-for-libraries/BUILD.bazel
  aio/content/examples/service-worker-getting-started/example-config.json
  aio/content/examples/setup/example-config.json
  aio/content/examples/testing/example-config.json
  aio/content/examples/toh-pt6/example-config.json
  aio/content/examples/universal/example-config.json
  aio/content/examples/upgrade-module/BUILD.bazel
  aio/content/examples/upgrade-phonecat-1-typescript/BUILD.bazel
  aio/content/examples/upgrade-phonecat-2-hybrid/BUILD.bazel
  aio/content/examples/upgrade-phonecat-3-final/BUILD.bazel
  aio/package.json
  aio/tools/defaults.bzl
  aio/tools/example-zipper/exampleZipper.mjs
  aio/tools/examples/BUILD.bazel
  aio/tools/examples/README.md
  aio/tools/examples/run-example-e2e.mjs
  aio/tools/examples/shared/BUILD.bazel
  aio/tools/examples/shared/boilerplate/cli/e2e/protractor-bazel.conf.js
  aio/tools/examples/shared/boilerplate/systemjs/protractor.config.js
  aio/tools/examples/shared/package.json
  aio/tools/examples/shared/yarn.lock
  aio/tools/ng-packages-installer/BUILD.bazel
  aio/tools/ng-packages-installer/index.js
  aio/tools/ng-packages-installer/node_modules.bzl
  aio/yarn.lock
  integration/index.bzl
  packages.bzl
  packages/animations/BUILD.bazel
  packages/bazel/BUILD.bazel
  packages/common/BUILD.bazel
  packages/compiler-cli/BUILD.bazel
  packages/compiler/BUILD.bazel
  packages/core/BUILD.bazel
  packages/elements/BUILD.bazel
  packages/forms/BUILD.bazel
  packages/language-service/BUILD.bazel
  packages/platform-browser-dynamic/BUILD.bazel
  packages/platform-browser/BUILD.bazel
  packages/platform-server/BUILD.bazel
  packages/router/BUILD.bazel
  packages/service-worker/BUILD.bazel
  packages/upgrade/BUILD.bazel
  yarn.bzl
Labels: comp: build & ci

#47113 Bump version to "v14.2.0-next.1" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, comp: build & ci, target: minor, PullApprove: disable

#47114 Bump version to "v14.1.2" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, comp: build & ci, target: patch, PullApprove: disable

#47115 docs: release notes for the v14.1.2 release
  CHANGELOG.md
Labels: action: merge, comp: build & ci, PullApprove: disable

#47118 fix(common): set bound width and height onto host element
  packages/common/src/directives/ng_optimized_image/ng_optimized_image.ts
  packages/common/test/directives/ng_optimized_image_spec.ts
Labels: comp: common, PullApprove: disable, target: feature

#47107 build(bazel): stamp targets to build, test, and serve aio against first party deps
  .bazelrc
  aio/BUILD.bazel
  aio/local_packages_util.bzl
  aio/tools/defaults.bzl
  packages/animations/BUILD.bazel
  packages/bazel/BUILD.bazel
  packages/bazel/src/ng_package/ng_package.bzl
  packages/benchpress/BUILD.bazel
  packages/common/BUILD.bazel
  packages/compiler-cli/BUILD.bazel
  packages/compiler/BUILD.bazel
  packages/core/BUILD.bazel
  packages/core/schematics/BUILD.bazel
  packages/elements/BUILD.bazel
  packages/forms/BUILD.bazel
  packages/language-service/BUILD.bazel
  packages/localize/BUILD.bazel
  packages/localize/schematics/BUILD.bazel
  packages/misc/angular-in-memory-web-api/BUILD.bazel
  packages/platform-browser-dynamic/BUILD.bazel
  packages/platform-browser/BUILD.bazel
  packages/platform-server/BUILD.bazel
  packages/router/BUILD.bazel
  packages/service-worker/BUILD.bazel
  packages/upgrade/BUILD.bazel
  packages/zone.js/BUILD.bazel
  tools/defaults.bzl
Labels: action: merge, comp: build & ci, target: feature

#47134 refactor(common): clean up util.ts and preconnect_link_checker.ts files
  packages/common/src/directives/ng_optimized_image/error_helper.ts
  packages/common/src/directives/ng_optimized_image/image_loaders/image_loader.ts
  packages/common/src/directives/ng_optimized_image/lcp_image_observer.ts
  packages/common/src/directives/ng_optimized_image/ng_optimized_image.ts
  packages/common/src/directives/ng_optimized_image/preconnect_link_checker.ts
  packages/common/src/directives/ng_optimized_image/url.ts
  packages/common/test/image_loaders/image_loader_spec.ts
Labels: comp: common, PullApprove: disable, target: feature

#47137 refactor(common): various NgOptimizedImage directive updates
  .circleci/config.yml
  goldens/public-api/common/index.md
  packages/common/src/directives/ng_optimized_image/asserts.ts
  packages/common/src/directives/ng_optimized_image/image_loaders/cloudflare_loader.ts
  packages/common/src/directives/ng_optimized_image/image_loaders/cloudinary_loader.ts
  packages/common/src/directives/ng_optimized_image/image_loaders/image_loader.ts
  packages/common/src/directives/ng_optimized_image/image_loaders/imagekit_loader.ts
  packages/common/src/directives/ng_optimized_image/image_loaders/imgix_loader.ts
  packages/common/src/directives/ng_optimized_image/lcp_image_observer.ts
  packages/common/src/directives/ng_optimized_image/ng_optimized_image.ts
  packages/common/src/directives/ng_optimized_image/preconnect_link_checker.ts
  packages/common/test/directives/ng_optimized_image_spec.ts
Labels: comp: common, PullApprove: disable, target: feature

#47142 refactor(common): address review feedback for NgOptimizedImage
  goldens/public-api/common/index.md
  packages/common/src/common.ts
  packages/common/src/directives/ng_optimized_image/image_loaders/cloudflare_loader.ts
  packages/common/src/directives/ng_optimized_image/image_loaders/cloudinary_loader.ts
  packages/common/src/directives/ng_optimized_image/image_loaders/image_loader.ts
  packages/common/src/directives/ng_optimized_image/ng_optimized_image.ts
  packages/common/test/directives/ng_optimized_image_spec.ts
Labels: action: review, comp: common

#47120 feat(common): warn if rendered size is much smaller than intrinsic
  goldens/public-api/common/errors.md
  packages/common/src/directives/ng_optimized_image/ng_optimized_image.ts
  packages/common/src/errors.ts
  packages/core/test/bundling/image-directive/BUILD.bazel
  packages/core/test/bundling/image-directive/e2e/image-distortion/image-distortion.ts
  packages/core/test/bundling/image-directive/e2e/logo-1500w.jpg
  packages/core/test/bundling/image-directive/e2e/logo-500w.jpg
  packages/core/test/bundling/image-directive/e2e/oversized-image/oversized-image.e2e-spec.ts
  packages/core/test/bundling/image-directive/e2e/oversized-image/oversized-image.ts
  packages/core/test/bundling/image-directive/e2e/preconnect-check/preconnect-check.e2e-spec.ts
  packages/core/test/bundling/image-directive/index.ts
  packages/core/test/bundling/image-directive/playground.ts
Labels: comp: common, PullApprove: disable, target: feature

#47147 refactor(common): minor NgOptimizedImage directive updates
  packages/common/src/directives/ng_optimized_image/lcp_image_observer.ts
  packages/common/src/directives/ng_optimized_image/ng_optimized_image.ts
  packages/core/test/bundling/image-directive/BUILD.bazel
  packages/core/test/bundling/image-directive/e2e/basic/basic.e2e-spec.ts
  packages/core/test/bundling/image-directive/e2e/browser-logs-util.ts
  packages/core/test/bundling/image-directive/e2e/image-distortion/image-distortion.e2e-spec.ts
  packages/core/test/bundling/image-directive/e2e/lcp-check/lcp-check.e2e-spec.ts
  packages/core/test/bundling/image-directive/e2e/oversized-image/oversized-image.e2e-spec.ts
  packages/core/test/bundling/image-directive/e2e/preconnect-check/preconnect-check.e2e-spec.ts
  packages/core/test/bundling/image-directive/e2e/start-server.js
Labels: comp: common, PullApprove: disable, target: feature

#47173 Bump version to "v14.1.3" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, comp: build & ci, PullApprove: disable

#47174 docs: release notes for the v14.1.3 release
  CHANGELOG.md
Labels: action: merge, comp: build & ci, PullApprove: disable

#47175 Bump version to "v14.2.0-rc.0" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, comp: build & ci, PullApprove: disable

#47265 Bump version to "v14.2.0" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, comp: build & ci, target: rc, PullApprove: disable

#47266 docs: release notes for the v14.2.0 release
  CHANGELOG.md
Labels: action: merge, comp: docs, comp: build & ci, target: minor, PullApprove: disable

#47268 Bump version to "v15.0.0-next.0" with changelog.
  CHANGELOG.md
Labels: action: merge, comp: build & ci, target: major, PullApprove: disable
