Repository angular/angular, pull requests merged in 2022-07, with the labels that each got.

#46724 Bump version to "v14.0.5" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, comp: build & ci, PullApprove: disable

#46725 docs: release notes for the v14.0.5 release
  CHANGELOG.md
Labels: action: merge, comp: build & ci, PullApprove: disable

#46533 build(bazel): fix race conditions in windows aio build
  WORKSPACE
  aio/BUILD.bazel
  aio/scripts/BUILD.bazel
  aio/tools/BUILD.bazel
  aio/tools/defaults.bzl
  aio/tools/esm-loader/BUILD.bazel
  aio/tools/esm-loader/esm-loader.mjs
  aio/tools/example-zipper/BUILD.bazel
  aio/tools/example-zipper/exampleZipper.mjs
  aio/tools/examples/BUILD.bazel
  aio/tools/stackblitz-builder/BUILD.bazel
  aio/tools/stackblitz-builder/builder.mjs
  aio/tools/transforms/examples-package/BUILD.bazel
  aio/tools/transforms/examples-package/services/region-parser.js
  aio/tools/transforms/helpers/BUILD.bazel
  third_party/github.com/lukeed/resolve.exports/BUILD.bazel
  third_party/github.com/lukeed/resolve.exports/LOCAL_MODS.md
  third_party/github.com/lukeed/resolve.exports/index.mjs
  third_party/github.com/lukeed/resolve.exports/license
  tools/bazel-repo-patches/rules_nodejs__esm_no_linker_fix.patch
Labels: comp: bazel

#46774 build(bazel): remove rules_nodejs patch
  WORKSPACE
  tools/bazel-repo-patches/rules_nodejs__esm_no_linker_fix.patch
Labels: action: merge, comp: build & ci, target: patch

#46827 Bump version to "v14.0.6" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, comp: build & ci, PullApprove: disable

#46828 docs: release notes for the v14.0.6 release
  CHANGELOG.md
Labels: action: merge, comp: build & ci, PullApprove: disable

#46830 Bump version to "v14.1.0-rc.0" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, comp: build & ci, PullApprove: disable

#46894 test(common): add parent injector to the `createEnvironmentInjector` calls in tests
  packages/common/test/image_loaders/image_loader_spec.ts
Labels: comp: common, PullApprove: disable, target: feature

#46907 Bump version to "v14.0.7" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, comp: build & ci, PullApprove: disable

#46908 docs: release notes for the v14.0.7 release
  CHANGELOG.md
Labels: action: merge, comp: build & ci, PullApprove: disable

#46909 Bump version to "v14.1.0" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, comp: build & ci, PullApprove: disable

#46855 feat(common): explain why width/height is required
  packages/common/src/directives/ng_optimized_image/ng_optimized_image.ts
  packages/common/test/directives/ng_optimized_image_spec.ts
Labels: action: merge, comp: common, PullApprove: disable, target: feature

#46932 refactor(common): update error messages of NgOptimizedImage directive
  packages/common/src/directives/ng_optimized_image/image_loaders/image_loader.ts
  packages/common/src/directives/ng_optimized_image/lcp_image_observer.ts
  packages/common/src/directives/ng_optimized_image/ng_optimized_image.ts
  packages/common/src/directives/ng_optimized_image/preconnect_link_checker.ts
  packages/common/src/directives/ng_optimized_image/util.ts
  packages/common/test/directives/ng_optimized_image_spec.ts
  packages/common/test/image_loaders/image_loader_spec.ts
  packages/core/test/bundling/image-directive/e2e/image-distortion/image-distortion.e2e-spec.ts
Labels: action: merge, comp: common, PullApprove: disable, target: feature
