Repository angular/angular, pull requests merged in 2023-11, with the labels that each got.

#52497 Bump version to "v16.2.12" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, area: build & ci, target: patch, PullApprove: disable

#52498 docs: release notes for the v16.2.12 release
  CHANGELOG.md
Labels: action: merge, area: docs, target: minor, PullApprove: disable

#52500 Bump version to "v17.0.0-rc.2" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, area: build & ci, target: rc, PullApprove: disable

#52501 docs: release notes for the v17.0.0-rc.2 release
  CHANGELOG.md
Labels: action: merge, area: docs, target: minor, PullApprove: disable

#52557 Bump version to "v17.0.0-rc.3" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, PullApprove: disable

#52558 docs: release notes for the v17.0.0-rc.3 release
  CHANGELOG.md
Labels: action: merge, area: docs, PullApprove: disable

#52625 Bump version to "v17.0.0" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, PullApprove: disable

#52626 docs: release notes for the v17.0.0 release
  CHANGELOG.md
Labels: action: merge, area: docs, PullApprove: disable

#52694 Bump version to "v17.0.1" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, PullApprove: disable

#52696 docs: release notes for the v17.0.1 release
  CHANGELOG.md
Labels: action: merge, area: docs, PullApprove: disable

#52752 Bump version to "v17.0.2" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, PullApprove: disable

#52754 docs: release notes for the v17.0.2 release
  CHANGELOG.md
Labels: action: merge, PullApprove: disable, area: docs

#52941 Bump version to "v17.0.3" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, PullApprove: disable

#52942 docs: release notes for the v17.0.3 release
  CHANGELOG.md
Labels: action: merge, PullApprove: disable, area: docs

#52943 Bump version to "v17.1.0-next.0" with changelog.
  CHANGELOG.md
Labels: action: merge, PullApprove: disable

#53062 Bump version to "v17.0.4" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, PullApprove: disable

#53063 docs: release notes for the v17.0.4 release
  CHANGELOG.md
Labels: action: merge, PullApprove: disable, area: docs

#53065 Bump version to "v17.1.0-next.1" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, PullApprove: disable

#53259 docs: release notes for the v17.0.5 release
  CHANGELOG.md
Labels: action: merge, PullApprove: disable, area: docs

#53260 Bump version to "v17.1.0-next.2" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, PullApprove: disable
