Repository angular/angular, pull requests merged in 2023-10, with the labels that each got.

#52028 Bump version to "v15.2.10" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, PullApprove: disable

#52030 docs: release notes for the v15.2.10 release
  CHANGELOG.md
Labels: action: merge, area: docs, PullApprove: disable

#52031 Bump version to "v16.2.8" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, PullApprove: disable

#52033 docs: release notes for the v16.2.8 release
  CHANGELOG.md
Labels: action: merge, area: build & ci, PullApprove: disable

#52036 Bump version to "v17.0.0-next.7" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, PullApprove: disable

#52127 build: fix broken symbols test
  packages/core/test/bundling/defer/bundle.golden_symbols.json
Labels: action: merge, area: build & ci, target: major

#52163 Bump version to "v16.2.9" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, PullApprove: disable

#52164 docs: release notes for the v16.2.9 release
  CHANGELOG.md
Labels: action: merge, area: docs, PullApprove: disable

#52165 Bump version to "v17.0.0-next.8" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, PullApprove: disable

#52264 Bump version to "v17.0.0-rc.0" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, PullApprove: disable

#52266 docs: release notes for the v17.0.0-rc.0 release
  CHANGELOG.md
Labels: action: merge, area: docs, PullApprove: disable

#52381 Bump version to "v16.2.11" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, area: build & ci, PullApprove: disable

#52382 docs: release notes for the v16.2.11 release
  CHANGELOG.md
Labels: action: merge, area: build & ci, PullApprove: disable

#52383 Bump version to "v17.0.0-rc.1" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, area: build & ci, PullApprove: disable

#52384 docs: release notes for the v17.0.0-rc.1 release
  CHANGELOG.md
Labels: action: merge, area: build & ci, PullApprove: disable
