Repository angular/angular, pull requests merged in 2023-07, with the labels that each got.

#50966 Bump version to "v16.1.4" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, PullApprove: disable

#50967 docs: release notes for the v16.1.4 release
  CHANGELOG.md
Labels: action: merge, area: docs, PullApprove: disable

#51033 Bump version to "v16.1.5" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, PullApprove: disable

#51034 docs: release notes for the v16.1.5 release
  CHANGELOG.md
Labels: action: merge, area: build & ci, PullApprove: disable

#51035 Bump version to "v16.2.0-next.2" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, PullApprove: disable

#51108 Bump version to "v16.1.6" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, PullApprove: disable

#51109 docs: release notes for the v16.1.6 release
  CHANGELOG.md
Labels: action: merge, area: docs, PullApprove: disable

#51111 Bump version to "v16.2.0-next.3" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, PullApprove: disable

#51177 Bump version to "v16.1.7" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, PullApprove: disable

#51178 docs: release notes for the v16.1.7 release
  CHANGELOG.md
Labels: action: merge, area: build & ci, PullApprove: disable
