Repository angular/angular, pull requests merged in 2023-03, with the labels that each got.

#49279 Bump version to "v15.2.1" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, area: build & ci, PullApprove: disable

#49280 docs: release notes for the v15.2.1 release
  CHANGELOG.md
Labels: action: merge, area: build & ci, PullApprove: disable

#49281 Bump version to "v16.0.0-next.1" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, PullApprove: disable

#49284 build: setup remote execution through shared command
  .circleci/config.yml
  .circleci/env.linux.sh
  .circleci/env.windows.sh
  .circleci/gcp_token
  .nvmrc
  WORKSPACE
  integration/bazel_workspace_tests/bazel_ngtsc_plugin/WORKSPACE
  scripts/ci/run_angular_components_unit_tests.sh
Labels: action: merge, area: build & ci, target: lts

#49278 Backport NgOptimizedImage to Angular 14
  aio/content/guide/image-directive-setup.md
  aio/content/guide/image-directive.md
  aio/content/navigation.json
  goldens/public-api/common/errors.md
  goldens/public-api/common/index.md
  packages/common/src/directives/ng_optimized_image/image_loaders/cloudflare_loader.ts
  packages/common/src/directives/ng_optimized_image/image_loaders/cloudinary_loader.ts
  packages/common/src/directives/ng_optimized_image/image_loaders/image_loader.ts
  packages/common/src/directives/ng_optimized_image/image_loaders/imagekit_loader.ts
  packages/common/src/directives/ng_optimized_image/image_loaders/imgix_loader.ts
  packages/common/src/directives/ng_optimized_image/index.ts
  packages/common/src/directives/ng_optimized_image/ng_optimized_image.ts
  packages/common/src/directives/ng_optimized_image/preconnect_link_checker.ts
  packages/common/src/directives/ng_optimized_image/preload-link-creator.ts
  packages/common/src/directives/ng_optimized_image/tokens.ts
  packages/common/src/errors.ts
  packages/common/test/directives/ng_optimized_image_spec.ts
  packages/common/test/image_loaders/image_loader_spec.ts
  packages/core/test/bundling/image-directive/BUILD.bazel
  packages/core/test/bundling/image-directive/e2e/browser-logs-util.ts
  packages/core/test/bundling/image-directive/e2e/fill-mode/fill-mode.e2e-spec.ts
  packages/core/test/bundling/image-directive/e2e/fill-mode/fill-mode.ts
  packages/core/test/bundling/image-directive/e2e/image-distortion/image-distortion.e2e-spec.ts
  packages/core/test/bundling/image-directive/e2e/image-distortion/image-distortion.ts
  packages/core/test/bundling/image-directive/e2e/oversized-image/oversized-image.ts
  packages/core/test/bundling/image-directive/e2e/start-server.js
  packages/core/test/bundling/image-directive/index.ts
Labels: action: merge, state: blocked, area: common, target: lts, merge: caretaker note

#49369 Bump version to "v15.2.2" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, PullApprove: disable

#49370 docs: release notes for the v15.2.2 release
  CHANGELOG.md
Labels: action: merge, area: docs, PullApprove: disable

#49371 Bump version to "v16.0.0-next.2" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, PullApprove: disable

#49412 Bump version to "v14.3.0" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, area: build & ci, PullApprove: disable

#49413 docs: release notes for the v14.3.0 release
  CHANGELOG.md
Labels: action: merge, area: docs, PullApprove: disable

#49450 Bump version to "v15.2.3" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, target: patch, PullApprove: disable

#49451 docs: release notes for the v15.2.3 release
  CHANGELOG.md
Labels: action: merge, area: docs, target: minor, PullApprove: disable

#49550 Bump version to "v15.2.4" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, PullApprove: disable

#49551 docs: release notes for the v15.2.4 release
  CHANGELOG.md
Labels: action: merge, area: docs, PullApprove: disable

#49552 Bump version to "v16.0.0-next.4" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, PullApprove: disable

#49635 Bump version to "v15.2.5" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, PullApprove: disable

#49636 docs: release notes for the v15.2.5 release
  CHANGELOG.md
Labels: action: merge, area: docs, PullApprove: disable

#49640 Bump version to "v16.0.0-next.5" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, PullApprove: disable
