Repository angular/angular, pull requests merged in 2023-08, with the labels that each got.

#51255 docs: release notes for the v16.1.8 release
  CHANGELOG.md
Labels: action: merge, area: docs, PullApprove: disable

#51256 Bump version to "v16.2.0-rc.0" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, PullApprove: disable

#51310 Bump version to "v16.1.9" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, PullApprove: disable

#51311 docs: release notes for the v16.1.9 release
  CHANGELOG.md
Labels: action: merge, area: build & ci, PullApprove: disable

#51312 Bump version to "v16.2.0" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, PullApprove: disable

#51313 docs: release notes for the v16.2.0 release
  CHANGELOG.md
Labels: action: merge, area: docs, PullApprove: disable

#51335 Configure next branch to receive major changes for v17.0.0-next.0
  package.json
Labels: action: merge, PullApprove: disable

#51387 Bump version to "v16.2.1" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, PullApprove: disable

#51388 docs: release notes for the v16.2.1 release
  CHANGELOG.md
Labels: action: merge, area: docs, PullApprove: disable

#51389 Bump version to "v17.0.0-next.0" with changelog.
  CHANGELOG.md
Labels: action: merge, PullApprove: disable

#51478 Bump version to "v16.2.2" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, PullApprove: disable

#51480 docs: release notes for the v16.2.2 release
  CHANGELOG.md
Labels: action: merge, area: docs, PullApprove: disable

#51481 Bump version to "v17.0.0-next.1" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, PullApprove: disable

#51582 Bump version to "v16.2.3" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, PullApprove: disable

#51583 docs: release notes for the v16.2.3 release
  CHANGELOG.md
Labels: action: merge, area: docs, PullApprove: disable

#51584 Bump version to "v17.0.0-next.2" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, PullApprove: disable
