Repository angular/angular, pull requests merged in 2023-04, with the labels that each got.

#49690 Bump version to "v16.0.0-next.6" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, area: build & ci, PullApprove: disable

#49724 Bump version to "v15.2.6" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, PullApprove: disable

#49725 docs: release notes for the v15.2.6 release
  CHANGELOG.md
Labels: action: merge, area: build & ci, PullApprove: disable

#49726 Bump version to "v16.0.0-next.7" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, PullApprove: disable

#49486 Backport NgOptimizedImage to v13
  .pullapprove.yml
  aio/content/guide/image-directive.md
  aio/content/navigation.json
  goldens/public-api/common/errors.md
  goldens/public-api/common/index.md
  goldens/size-tracking/integration-payloads.json
  packages/common/src/common.ts
  packages/common/src/directives/index.ts
  packages/common/src/directives/ng_optimized_image/asserts.ts
  packages/common/src/directives/ng_optimized_image/error_helper.ts
  packages/common/src/directives/ng_optimized_image/image_loaders/cloudflare_loader.ts
  packages/common/src/directives/ng_optimized_image/image_loaders/cloudinary_loader.ts
  packages/common/src/directives/ng_optimized_image/image_loaders/image_loader.ts
  packages/common/src/directives/ng_optimized_image/image_loaders/imagekit_loader.ts
  packages/common/src/directives/ng_optimized_image/image_loaders/imgix_loader.ts
  packages/common/src/directives/ng_optimized_image/index.ts
  packages/common/src/directives/ng_optimized_image/lcp_image_observer.ts
  packages/common/src/directives/ng_optimized_image/ng_optimized_image.ts
  packages/common/src/directives/ng_optimized_image/preconnect_link_checker.ts
  packages/common/src/directives/ng_optimized_image/preload-link-creator.ts
  packages/common/src/directives/ng_optimized_image/tokens.ts
  packages/common/src/directives/ng_optimized_image/url.ts
  packages/common/src/errors.ts
  packages/common/test/directives/ng_optimized_image_spec.ts
  packages/common/test/image_loaders/image_loader_spec.ts
  packages/core/src/core_private_export.ts
  packages/core/test/bundling/image-directive/BUILD.bazel
  packages/core/test/bundling/image-directive/README.md
  packages/core/test/bundling/image-directive/e2e/a.png
  packages/core/test/bundling/image-directive/e2e/b.png
  packages/core/test/bundling/image-directive/e2e/basic/basic.e2e-spec.ts
  packages/core/test/bundling/image-directive/e2e/basic/basic.ts
  packages/core/test/bundling/image-directive/e2e/browser-logs-util.ts
  packages/core/test/bundling/image-directive/e2e/fill-mode/fill-mode.e2e-spec.ts
  packages/core/test/bundling/image-directive/e2e/fill-mode/fill-mode.ts
  packages/core/test/bundling/image-directive/e2e/image-distortion/image-distortion.e2e-spec.ts
  packages/core/test/bundling/image-directive/e2e/image-distortion/image-distortion.ts
  packages/core/test/bundling/image-directive/e2e/lcp-check/lcp-check.e2e-spec.ts
  packages/core/test/bundling/image-directive/e2e/lcp-check/lcp-check.ts
  packages/core/test/bundling/image-directive/e2e/logo-1500w.jpg
  packages/core/test/bundling/image-directive/e2e/logo-500w.jpg
  packages/core/test/bundling/image-directive/e2e/oversized-image/oversized-image.e2e-spec.ts
  packages/core/test/bundling/image-directive/e2e/oversized-image/oversized-image.ts
  packages/core/test/bundling/image-directive/e2e/preconnect-check/preconnect-check.e2e-spec.ts
  packages/core/test/bundling/image-directive/e2e/preconnect-check/preconnect-check.ts
  packages/core/test/bundling/image-directive/e2e/start-server.js
  packages/core/test/bundling/image-directive/e2e/tsconfig-e2e.json
  packages/core/test/bundling/image-directive/index.html
  packages/core/test/bundling/image-directive/index.ts
  packages/core/test/bundling/image-directive/playground.ts
  packages/private/testing/src/render3.ts
Labels: area: common, target: lts, common: image directive

#49736 Bump version to "v13.4.0" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, area: build & ci, PullApprove: disable

#49738 docs: release notes for the v13.4.0 release
  CHANGELOG.md
Labels: action: merge, area: docs, PullApprove: disable

#49817 Bump version to "v15.2.7" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, PullApprove: disable

#49820 Bump version to "v16.0.0-rc.0" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, PullApprove: disable

#49821 docs: release notes for the v16.0.0-rc.0 release
  CHANGELOG.md
Labels: action: merge, area: build & ci, PullApprove: disable

#49844 Bump version to "v16.0.0-rc.1" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, PullApprove: disable

#49845 docs: release notes for the v16.0.0-rc.1 release
  CHANGELOG.md
Labels: action: merge, area: docs, PullApprove: disable

#49935 Bump version to "v15.2.8" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, PullApprove: disable

#49936 docs: release notes for the v15.2.8 release
  CHANGELOG.md
Labels: action: merge, area: docs, PullApprove: disable

#49938 Bump version to "v16.0.0-rc.2" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, PullApprove: disable

#49939 docs: release notes for the v16.0.0-rc.2 release
  CHANGELOG.md
Labels: action: merge, area: docs, PullApprove: disable

#50040 Bump version to "v16.0.0-rc.3" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, PullApprove: disable
