Repository angular/angular, pull requests merged in 2023-06, with the labels that each got.

#50540 Bump version to "v16.0.4" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, PullApprove: disable

#50541 docs: release notes for the v16.0.4 release
  CHANGELOG.md
Labels: action: merge, area: build & ci, PullApprove: disable

#50622 Bump version to "v16.1.0-rc.0" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, PullApprove: disable

#50624 Bump version to "v16.0.5" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, PullApprove: disable

#50625 docs: release notes for the v16.0.5 release
  CHANGELOG.md
Labels: action: merge, area: docs, PullApprove: disable

#50703 Bump version to "v16.0.6" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, PullApprove: disable

#50704 docs: release notes for the v16.0.6 release
  CHANGELOG.md
Labels: action: merge, area: docs, PullApprove: disable

#50705 Bump version to "v16.1.0" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, PullApprove: disable

#50706 docs: release notes for the v16.1.0 release
  CHANGELOG.md
Labels: action: merge, area: docs, PullApprove: disable

#50721 Bump version to "v16.1.1" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, PullApprove: disable

#50768 build: resolve benchmark compare ref from upstream if rev-parse fails
  scripts/benchmarks/index.mts
Labels: action: merge, area: build & ci, target: minor

#50796 Bump version to "v16.1.2" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, PullApprove: disable

#50797 docs: release notes for the v16.1.2 release
  CHANGELOG.md
Labels: action: merge, area: build & ci, PullApprove: disable

#50798 Bump version to "v16.2.0-next.0" with changelog.
  CHANGELOG.md
Labels: action: merge, PullApprove: disable

#50806 docs: fix typos
  CHANGELOG_ARCHIVE.md
Labels: area: docs

#50872 Bump version to "v16.1.3" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, PullApprove: disable

#50873 docs: release notes for the v16.1.3 release
  CHANGELOG.md
Labels: action: merge, area: docs, PullApprove: disable

#50874 Bump version to "v16.2.0-next.1" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, area: build & ci, PullApprove: disable

#50909 ci: reduce benchmark compare permissions
  .github/workflows/benchmark-compare.yml
Labels: area: build & ci, action: review, target: minor
