Repository angular/angular, pull requests merged in 2023-05, with the labels that each got.

#50094 docs: release notes for the v16.0.0-rc.4 release
  CHANGELOG.md
Labels: action: merge, area: docs, target: minor, PullApprove: disable

#50124 Bump version to "v15.2.9" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, PullApprove: disable

#50125 docs: release notes for the v15.2.9 release
  CHANGELOG.md
Labels: action: merge, area: docs, PullApprove: disable

#50126 Bump version to "v16.0.0" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, PullApprove: disable

#50127 docs: release notes for the v16.0.0 release
  CHANGELOG.md
Labels: action: merge, area: docs, PullApprove: disable

#50239 Bump version to "v16.0.1" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, area: build & ci, PullApprove: disable

#50240 docs: release notes for the v16.0.1 release
  CHANGELOG.md
Labels: action: merge, area: build & ci, PullApprove: disable

#50241 Bump version to "v16.1.0-next.0" with changelog.
  CHANGELOG.md
Labels: action: merge, area: build & ci, PullApprove: disable

#50350 Bump version to "v16.0.2" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, PullApprove: disable

#50351 docs: release notes for the v16.0.2 release
  CHANGELOG.md
Labels: action: merge, area: build & ci, PullApprove: disable

#50449 Bump version to "v16.0.3" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, PullApprove: disable

#50450 docs: release notes for the v16.0.3 release
  CHANGELOG.md
Labels: action: merge, area: docs, PullApprove: disable

#50452 Bump version to "v16.1.0-next.2" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, PullApprove: disable
