Repository angular/angular, pull requests merged in 2023-09, with the labels that each got.

#51680 Bump version to "v17.0.0-next.3" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, PullApprove: disable

#51759 Bump version to "v16.2.5" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, PullApprove: disable

#51760 docs: release notes for the v16.2.5 release
  CHANGELOG.md
Labels: action: merge, area: docs, area: build & ci, PullApprove: disable

#51762 Bump version to "v17.0.0-next.4" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, area: build & ci, PullApprove: disable

#51835 Bump version to "v16.2.6" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, PullApprove: disable

#51836 docs: release notes for the v16.2.6 release
  CHANGELOG.md
Labels: action: merge, area: docs, PullApprove: disable

#51837 Bump version to "v17.0.0-next.5" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, PullApprove: disable

#51935 Bump version to "v16.2.7" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, area: build & ci, PullApprove: disable

#51936 docs: release notes for the v16.2.7 release
  CHANGELOG.md
Labels: action: merge, area: build & ci, PullApprove: disable

#51937 Bump version to "v17.0.0-next.6" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, PullApprove: disable
