Repository angular/angular, pull requests merged in 2023-01, with the labels that each got.

#48649 Bump version to "v15.1.0-rc.0" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, target: minor, PullApprove: disable

#48685 Bump version to "v15.1.0" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, PullApprove: disable

#48686 docs: release notes for the v15.1.0 release
  CHANGELOG.md
Labels: action: merge, area: docs, PullApprove: disable

#48699 Bump version to "v15.2.0-next.0" with changelog.
  CHANGELOG.md
Labels: action: merge, PullApprove: disable

#48769 Bump version to "v15.1.1" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, PullApprove: disable

#48770 docs: release notes for the v15.1.1 release
  CHANGELOG.md
Labels: action: merge, area: build & ci, PullApprove: disable

#48771 Bump version to "v15.2.0-next.1" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, PullApprove: disable

#48840 Bump version to "v15.1.2" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, PullApprove: disable

#48842 Bump version to "v15.2.0-next.2" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, PullApprove: disable
