Repository angular/angular, pull requests merged in 2023-12, with the labels that each got.

#53401 Bump version to "v17.0.6" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, area: build & ci, PullApprove: disable

#53402 docs: release notes for the v17.0.6 release
  CHANGELOG.md
Labels: action: merge, PullApprove: disable, area: docs

#53403 Bump version to "v17.1.0-next.3" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, area: build & ci, PullApprove: disable

#53561 Bump version to "v17.0.7" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, target: patch, PullApprove: disable

#53562 docs: release notes for the v17.0.7 release
  CHANGELOG.md
Labels: action: merge, target: minor, PullApprove: disable, area: docs

#53563 Bump version to "v17.1.0-next.4" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, area: build & ci, target: minor, PullApprove: disable

#53674 Bump version to "v17.0.8" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, PullApprove: disable

#53675 docs: release notes for the v17.0.8 release
  CHANGELOG.md
Labels: action: merge, PullApprove: disable, area: docs

#53676 Bump version to "v17.1.0-next.5" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, PullApprove: disable
