Repository angular/angular, pull requests merged in 2024-05, with the labels that each got.

#55612 Bump version to "v17.3.7" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, PullApprove: disable

#55613 docs: release notes for the v17.3.7 release
  CHANGELOG.md
Labels: action: merge, area: build & ci, PullApprove: disable

#55614 Bump version to "v18.0.0-rc.0" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, PullApprove: disable

#55615 docs: release notes for the v18.0.0-rc.0 release
  CHANGELOG.md
Labels: action: merge, PullApprove: disable, area: docs

#55734 Bump version to "v17.3.8" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, PullApprove: disable

#55735 docs: release notes for the v17.3.8 release
  CHANGELOG.md
Labels: action: merge, PullApprove: disable, area: docs

#55736 Bump version to "v18.0.0-rc.1" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, PullApprove: disable

#55737 docs: release notes for the v18.0.0-rc.1 release
  CHANGELOG.md
Labels: action: merge, PullApprove: disable, area: docs

#55816 Bump version to "v17.3.9" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, PullApprove: disable

#55817 docs: release notes for the v17.3.9 release
  CHANGELOG.md
Labels: action: merge, PullApprove: disable, area: docs

#55819 Bump version to "v18.0.0-rc.2" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, PullApprove: disable

#55820 docs: release notes for the v18.0.0-rc.2 release
  CHANGELOG.md
Labels: action: merge, PullApprove: disable, area: docs

#55976 Bump version to "v18.0.0-rc.3" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, PullApprove: disable

#55978 docs: release notes for the v18.0.0-rc.3 release
  CHANGELOG.md
Labels: action: merge, PullApprove: disable, area: docs

#56005 Bump version to "v18.0.0" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, PullApprove: disable

#56006 docs: release notes for the v18.0.0 release
  CHANGELOG.md
Labels: action: merge, area: build & ci, PullApprove: disable

#56007 Bump version to "v17.3.10" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, PullApprove: disable

#56008 docs: release notes for the v17.3.10 release
  CHANGELOG.md
Labels: action: merge, PullApprove: disable, area: docs

#56156 Bump version to "v18.0.1" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, PullApprove: disable

#56158 docs: release notes for the v18.0.1 release
  CHANGELOG.md
Labels: action: merge, PullApprove: disable, area: docs

#56159 Bump version to "v18.1.0-next.0" with changelog.
  CHANGELOG.md
Labels: action: merge, PullApprove: disable
