Repository angular/angular, pull requests merged in 2024-11, with the labels that each got.

#58532 Bump version to "v18.2.11" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, PullApprove: disable

#58533 docs: release notes for the v18.2.11 release
  CHANGELOG.md
Labels: action: merge, PullApprove: disable, area: docs

#58534 Bump version to "v19.0.0-rc.1" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, PullApprove: disable

#58535 docs: release notes for the v19.0.0-rc.1 release
  CHANGELOG.md
Labels: action: merge, area: build & ci, PullApprove: disable

#58661 Bump version to "v18.2.12" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, PullApprove: disable

#58662 docs: release notes for the v18.2.12 release
  CHANGELOG.md
Labels: action: merge, area: build & ci, PullApprove: disable

#58664 Bump version to "v19.0.0-rc.2" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, PullApprove: disable

#58665 docs: release notes for the v19.0.0-rc.2 release
  CHANGELOG.md
Labels: action: merge, PullApprove: disable, area: docs

#58691 Bump version to "v19.0.0-rc.3" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, PullApprove: disable

#58692 docs: release notes for the v19.0.0-rc.3 release
  CHANGELOG.md
Labels: action: merge, PullApprove: disable, area: docs

#58734 Bump version to "v19.0.0" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, PullApprove: disable

#58735 docs: release notes for the v19.0.0 release
  CHANGELOG.md
Labels: action: merge, PullApprove: disable, area: docs

#58736 docs: improve changelog for v19
  CHANGELOG.md
Labels: action: review, target: minor, area: docs

#58903 Bump version to "v19.0.1" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, PullApprove: disable

#58905 docs: release notes for the v19.0.1 release
  CHANGELOG.md
Labels: action: merge, PullApprove: disable, area: docs

#58908 docs: release notes for the v18.2.13 release
  CHANGELOG.md
Labels: action: merge, PullApprove: disable, area: docs
