Repository angular/angular, pull requests merged in 2024-04, with the labels that each got.

#55203 Bump version to "v17.3.3" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, PullApprove: disable

#55204 Bump version to "v18.0.0-next.3" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, PullApprove: disable

#55296 Bump version to "v17.3.4" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, PullApprove: disable

#55297 docs: release notes for the v17.3.4 release
  CHANGELOG.md
Labels: action: merge, area: build & ci, PullApprove: disable

#55300 Bump version to "v18.0.0-next.4" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, area: build & ci, PullApprove: disable

#55382 Bump version to "v17.3.5" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, PullApprove: disable

#55384 docs: release notes for the v17.3.5 release
  CHANGELOG.md
Labels: action: merge, PullApprove: disable, area: docs

#55385 Bump version to "v18.0.0-next.5" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, PullApprove: disable

#55539 Bump version to "v17.3.6" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, PullApprove: disable

#55541 docs: release notes for the v17.3.6 release
  CHANGELOG.md
Labels: action: merge, area: build & ci, PullApprove: disable, area: docs

#55542 Bump version to "v18.0.0-next.6" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, PullApprove: disable
