Repository angular/angular, pull requests merged in 2024-08, with the labels that each got.

#57265 Bump version to "v18.2.0-next.4" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, PullApprove: disable

#57294 Bump version to "v18.1.4" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, PullApprove: disable

#57295 docs: release notes for the v18.1.4 release
  CHANGELOG.md
Labels: action: merge, PullApprove: disable, area: docs

#57296 Bump version to "v18.2.0-rc.0" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, area: build & ci, PullApprove: disable

#57398 Bump version to "v18.1.5" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, PullApprove: disable

#57399 docs: release notes for the v18.1.5 release
  CHANGELOG.md
Labels: action: merge, PullApprove: disable, area: docs

#57400 Bump version to "v18.2.0" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, PullApprove: disable

#57401 docs: release notes for the v18.2.0 release
  CHANGELOG.md
Labels: action: merge, PullApprove: disable, area: docs

#57403 Bump version to "v19.0.0-next.0" with changelog.
  CHANGELOG.md
Labels: action: merge, area: build & ci, PullApprove: disable

#57488 Bump version to "v19.0.0-next.1" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, area: build & ci, PullApprove: disable

#57489 Bump version to "v18.2.1" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, area: build & ci, PullApprove: disable

#57490 docs: release notes for the v18.2.1 release
  CHANGELOG.md
Labels: action: merge, PullApprove: disable, area: docs

#57573 Bump version to "v18.2.2" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, target: patch, PullApprove: disable

#57574 docs: release notes for the v18.2.2 release
  CHANGELOG.md
Labels: action: merge, area: build & ci, PullApprove: disable

#57575 Bump version to "v19.0.0-next.2" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, PullApprove: disable
