Repository angular/angular, pull requests merged in 2024-03, with the labels that each got.

#54728 docs: release notes for the v17.2.4 release
  CHANGELOG.md
Labels: action: merge, PullApprove: disable, area: docs

#54729 Bump version to "v17.3.0-rc.0" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, PullApprove: disable

#54737 release: bump the next branch to v18.0.0-next.0
  package.json
Labels: PullApprove: disable

#54758 Revert "refactor(compiler): rework defer block analysis (#54700)"
  packages/compiler-cli/linker/src/file_linker/partial_linkers/partial_component_linker_1.ts
  packages/compiler-cli/src/ngtsc/annotations/component/src/handler.ts
  packages/compiler-cli/src/ngtsc/annotations/component/src/metadata.ts
  packages/compiler/src/jit_compiler_facade.ts
  packages/compiler/src/render3/view/api.ts
  packages/compiler/src/render3/view/compiler.ts
  packages/compiler/src/render3/view/template.ts
  packages/compiler/src/template/pipeline/ir/src/ops/create.ts
  packages/compiler/src/template/pipeline/src/compilation.ts
  packages/compiler/src/template/pipeline/src/emit.ts
  packages/compiler/src/template/pipeline/src/ingest.ts
  packages/compiler/src/template/pipeline/src/phases/create_defer_deps_fns.ts
  packages/compiler/src/template/pipeline/src/phases/resolve_defer_deps_fns.ts
Labels: action: merge, target: major, PullApprove: disable

#54774 Revert "fix(core): `ApplicationRef.tick` should respect OnPush for ho…
  packages/core/src/application/application_ref.ts
  packages/core/src/render3/instructions/change_detection.ts
  packages/core/test/application_ref_spec.ts
Labels: target: major

#54845 Bump version to "v17.3.0" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, PullApprove: disable

#54846 docs: release notes for the v17.3.0 release
  CHANGELOG.md
Labels: action: merge, PullApprove: disable, area: docs

#54862 Bump version to "v18.0.0-next.0" with changelog.
  CHANGELOG.md
Labels: action: merge, PullApprove: disable

#54969 Bump version to "v17.3.1" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, PullApprove: disable

#54972 Bump version to "v18.0.0-next.1" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, PullApprove: disable

#55065 [17.3.x]: build: follow-up fixes for AIO lighthouse checks
  aio/package.json
  aio/scripts/audit-web-app.mjs
  aio/scripts/test-aio-a11y.mjs
  aio/yarn.lock
  goldens/size-tracking/aio-payloads.json
Labels: area: build & ci, action: review, target: patch, PullApprove: disable

#55093 Bump version to "v17.3.2" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, PullApprove: disable

#55094 docs: release notes for the v17.3.2 release
  CHANGELOG.md
Labels: action: merge, PullApprove: disable, area: docs

#55095 Bump version to "v18.0.0-next.2" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, area: build & ci, PullApprove: disable
