Repository angular/angular, pull requests merged in 2024-06, with the labels that each got.

#56285 Bump version to "v17.3.11" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, PullApprove: disable

#56288 Bump version to "v18.0.2" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, PullApprove: disable

#56289 docs: release notes for the v18.0.2 release
  CHANGELOG.md
Labels: action: merge, area: build & ci, PullApprove: disable

#56291 Bump version to "v18.1.0-next.1" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, PullApprove: disable

#56419 Bump version to "v18.0.3" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, PullApprove: disable

#56420 docs: release notes for the v18.0.3 release
  CHANGELOG.md
Labels: action: merge, PullApprove: disable, area: docs

#56421 Bump version to "v18.1.0-next.2" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, PullApprove: disable

#56529 Bump version to "v18.0.4" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, PullApprove: disable

#56530 docs: release notes for the v18.0.4 release
  CHANGELOG.md
Labels: action: merge, PullApprove: disable, area: docs

#56532 Bump version to "v18.1.0-next.3" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, PullApprove: disable

#56729 Bump version to "v18.1.0-next.4" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, PullApprove: disable

#56730 Bump version to "v18.0.5" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, area: build & ci, PullApprove: disable

#56731 docs: release notes for the v18.0.5 release
  CHANGELOG.md
Labels: action: merge, area: build & ci, PullApprove: disable
