Repository angular/angular, pull requests merged in 2024-12, with the labels that each got.

#59041 Bump version to "v19.0.2" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, PullApprove: disable

#59042 docs: release notes for the v19.0.2 release
  CHANGELOG.md
Labels: action: merge, PullApprove: disable, area: docs

#59043 Bump version to "v19.1.0-next.1" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, PullApprove: disable

#59054 Bump version to "v19.0.3" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, area: build & ci, PullApprove: disable

#59055 docs: release notes for the v19.0.3 release
  CHANGELOG.md
Labels: action: merge, PullApprove: disable, area: docs

#59056 Bump version to "v19.1.0-next.2" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, PullApprove: disable

#59167 Bump version to "v19.0.4" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, PullApprove: disable

#59236 Bump version to "v19.0.5" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, PullApprove: disable

#59237 docs: release notes for the v19.0.5 release
  CHANGELOG.md
Labels: action: merge, area: build & ci, PullApprove: disable

#59239 Bump version to "v19.1.0-next.4" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, PullApprove: disable
