Repository angular/angular, pull requests merged in 2024-09, with the labels that each got.

#57660 Bump version to "v18.2.3" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, PullApprove: disable

#57661 docs: release notes for the v18.2.3 release
  CHANGELOG.md
Labels: action: merge, area: build & ci, PullApprove: disable

#57662 Bump version to "v19.0.0-next.3" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, PullApprove: disable

#57742 Bump version to "v19.0.0-next.4" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, PullApprove: disable

#57780 Bump version to "v18.2.4" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, PullApprove: disable

#57781 docs: release notes for the v18.2.4 release
  CHANGELOG.md
Labels: action: merge, PullApprove: disable, area: docs

#57782 Bump version to "v19.0.0-next.5" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, PullApprove: disable

#57868 Bump version to "v18.2.5" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, PullApprove: disable

#57869 docs: release notes for the v18.2.5 release
  CHANGELOG.md
Labels: action: merge, PullApprove: disable, area: docs

#57870 Bump version to "v19.0.0-next.6" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, area: build & ci, PullApprove: disable

#57958 Bump version to "v18.2.6" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, PullApprove: disable

#57959 docs: release notes for the v18.2.6 release
  CHANGELOG.md
Labels: action: merge, PullApprove: disable, area: docs

#57960 Bump version to "v19.0.0-next.7" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, area: build & ci, PullApprove: disable
