Repository angular/angular, pull requests merged in 2024-07, with the labels that each got.

#56795 Bump version to "v18.1.0-rc.0" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, PullApprove: disable

#56834 docs: release notes for the v18.0.6 release
  CHANGELOG.md
Labels: action: merge, PullApprove: disable, area: docs

#56925 docs: release notes for the v18.0.7 release
  CHANGELOG.md
Labels: action: merge, PullApprove: disable, area: docs

#56926 Bump version to "v18.1.0" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, PullApprove: disable

#56927 docs: release notes for the v18.1.0 release
  CHANGELOG.md
Labels: action: merge, area: build & ci, PullApprove: disable

#56928 Bump version to "v18.2.0-next.0" with changelog.
  CHANGELOG.md
Labels: action: merge, PullApprove: disable

#57022 Bump version to "v17.3.12" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, PullApprove: disable

#57023 docs: release notes for the v17.3.12 release
  CHANGELOG.md
Labels: target: minor

#57025 Bump version to "v18.1.1" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, PullApprove: disable

#57026 docs: release notes for the v18.1.1 release
  CHANGELOG.md
Labels: action: merge, PullApprove: disable, area: docs

#57116 Bump version to "v18.1.2" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, PullApprove: disable

#57118 docs: release notes for the v18.1.2 release
  CHANGELOG.md
Labels: action: merge, PullApprove: disable, area: docs

#57120 Bump version to "v18.2.0-next.2" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, PullApprove: disable

#57175 ci: replace `matchDepPatterns` with `matchPackageNames`
  renovate.json
Labels: area: build & ci, action: review, target: patch

#57216 Bump version to "v18.1.3" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, PullApprove: disable

#57217 docs: release notes for the v18.1.3 release
  CHANGELOG.md
Labels: action: merge, area: build & ci, PullApprove: disable

#57218 Bump version to "v18.2.0-next.3" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, PullApprove: disable
