Repository angular/angular, pull requests merged in 2024-10, with the labels that each got.

#58045 Bump version to "v18.2.7" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, PullApprove: disable

#58046 docs: release notes for the v18.2.7 release
  CHANGELOG.md
Labels: action: merge, PullApprove: disable, area: docs

#58047 Bump version to "v19.0.0-next.8" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, PullApprove: disable

#58145 Bump version to "v18.2.8" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, PullApprove: disable

#58146 docs: release notes for the v18.2.8 release
  CHANGELOG.md
Labels: action: merge, PullApprove: disable, area: docs

#58147 Bump version to "v19.0.0-next.9" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, PullApprove: disable

#58230 Bump version to "v19.0.0-next.10" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, PullApprove: disable

#58334 Bump version to "v18.2.9" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, PullApprove: disable

#58335 docs: release notes for the v18.2.9 release
  CHANGELOG.md
Labels: action: merge, area: build & ci, PullApprove: disable

#58336 Bump version to "v19.0.0-next.11" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, PullApprove: disable

#58434 Bump version to "v18.2.10" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, PullApprove: disable

#58435 docs: release notes for the v18.2.10 release
  CHANGELOG.md
Labels: action: merge, PullApprove: disable, area: docs

#58437 Bump version to "v19.0.0-rc.0" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, PullApprove: disable

#58438 docs: release notes for the v19.0.0-rc.0 release
  CHANGELOG.md
Labels: action: merge, area: build & ci, PullApprove: disable
