Repository angular/angular, pull requests merged in 2025-08, with the labels that each got.

#63022 Bump version to "v20.1.5" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, area: build & ci, PullApprove: disable

#63023 docs: release notes for the v20.1.5 release
  CHANGELOG.md
Labels: action: merge, area: build & ci, PullApprove: disable, area: docs

#63031 Bump version to "v20.1.6" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, area: build & ci, PullApprove: disable

#63032 docs: release notes for the v20.1.6 release
  CHANGELOG.md
Labels: action: merge, area: build & ci, PullApprove: disable, area: docs

#63033 Bump version to "v20.2.0-next.5" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, area: build & ci, PullApprove: disable

#63056 Bump version to "v20.2.0-next.6" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, area: build & ci, PullApprove: disable

#63045 feat(forms): switch to RegExp in pattern validator
  goldens/public-api/forms/experimental/index.api.md
  packages/forms/experimental/src/api/property.ts
  packages/forms/experimental/src/api/validation_errors.ts
  packages/forms/experimental/src/api/validators/pattern.ts
  packages/forms/experimental/test/node/api/validators/pattern.spec.ts
  packages/forms/experimental/test/node/validation_status.spec.ts
Labels: area: build & ci, area: forms, target: feature, detected: feature, area: docs

#63058 refactor(forms): reorganize control directive & add disabled/readonly
  goldens/public-api/forms/experimental/index.api.md
  packages/forms/experimental/src/api/control.ts
  packages/forms/experimental/src/api/structure.ts
  packages/forms/experimental/src/api/types.ts
  packages/forms/experimental/src/controls/control.ts
  packages/forms/experimental/src/field/manager.ts
  packages/forms/experimental/src/field/node.ts
  packages/forms/experimental/src/field/property.ts
  packages/forms/experimental/src/field/state.ts
  packages/forms/experimental/src/util/illegal.ts
  packages/forms/experimental/test/node/BUILD.bazel
  packages/forms/experimental/test/node/control_directive.spec.ts
  packages/forms/experimental/test/node/field_node.spec.ts
Labels: area: build & ci, area: forms, target: feature, detected: feature, area: docs

#63060 feat(forms): track bound controls as field state
  goldens/public-api/forms/experimental/index.api.md
  packages/forms/experimental/src/api/types.ts
  packages/forms/experimental/src/controls/control.ts
  packages/forms/experimental/src/field/node.ts
  packages/forms/experimental/src/field/state.ts
  packages/forms/experimental/test/node/control_directive.spec.ts
Labels: area: forms, target: feature, detected: feature, area: docs

#63084 Bump version to "v20.2.0-rc.0" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, area: build & ci, PullApprove: disable

#63144 Bump version to "v20.1.7" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, area: build & ci, PullApprove: disable

#63146 Bump version to "v20.2.0-rc.1" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, area: build & ci, PullApprove: disable

#63147 docs: release notes for the v20.2.0-rc.1 release
  CHANGELOG.md
Labels: action: merge, area: build & ci, PullApprove: disable, area: docs

#63278 Bump version to "v20.2.0" with changelog.
  CHANGELOG.md
  MODULE.bazel.lock
  package.json
Labels: action: merge, area: build & ci, PullApprove: disable

#63280 docs: release notes for the v20.2.0 release
  CHANGELOG.md
  renovate.json
Labels: action: merge, area: build & ci, PullApprove: disable, area: docs

#63305 Bump version to "v20.2.1" with changelog.
  CHANGELOG.md
  MODULE.bazel.lock
  package.json
Labels: action: merge, area: build & ci, PullApprove: disable

#63306 docs: release notes for the v20.2.1 release
  CHANGELOG.md
Labels: action: merge, area: build & ci, PullApprove: disable

#63298 perf(forms): enable tree shaking of unused errors and properties
  packages/forms/signals/src/api/logic.ts
  packages/forms/signals/src/api/property.ts
  packages/forms/signals/src/api/validation_errors.ts
  packages/forms/signals/src/api/validators/email.ts
  packages/forms/signals/src/api/validators/max.ts
  packages/forms/signals/src/api/validators/max_length.ts
  packages/forms/signals/src/api/validators/min.ts
  packages/forms/signals/src/api/validators/min_length.ts
  packages/forms/signals/src/api/validators/pattern.ts
  packages/forms/signals/src/api/validators/required.ts
  packages/forms/signals/src/api/validators/standard_schema.ts
  packages/forms/signals/test/node/api/hidden.spec.ts
  packages/forms/signals/test/node/api/validators/email.spec.ts
  packages/forms/signals/test/node/api/validators/max.spec.ts
  packages/forms/signals/test/node/api/validators/max_length.spec.ts
  packages/forms/signals/test/node/api/validators/min.spec.ts
  packages/forms/signals/test/node/api/validators/min_length.spec.ts
  packages/forms/signals/test/node/api/validators/pattern.spec.ts
  packages/forms/signals/test/node/api/validators/required.spec.ts
  packages/forms/signals/test/node/api/when.spec.ts
  packages/forms/signals/test/node/field_node.spec.ts
  packages/forms/signals/test/node/logic_node.spec.ts
  packages/forms/signals/test/node/path.spec.ts
  packages/forms/signals/test/node/recursive_logic.spec.ts
  packages/forms/signals/test/node/resource.spec.ts
  packages/forms/signals/test/node/submit.spec.ts
  packages/forms/signals/test/node/validation_status.spec.ts
Labels: area: performance, area: forms, target: feature

#63322 docs(forms): address feedback on #63293
  packages/forms/BUILD.bazel
  packages/forms/signals/src/api/logic.ts
  packages/forms/signals/src/api/structure.ts
  packages/forms/signals/src/api/types.ts
  packages/forms/signals/src/api/validation_errors.ts
  packages/forms/signals/src/api/validators/required.ts
  packages/forms/signals/src/schema/logic_node.ts
  packages/forms/signals/test/node/BUILD.bazel
  packages/forms/signals/test/node/dynamic.spec.ts
  packages/forms/signals/test/node/field_context.spec.ts
  packages/forms/signals/test/node/field_node.spec.ts
  packages/forms/signals/test/node/logic_node.spec.ts
  packages/forms/signals/test/node/path.spec.ts
  packages/forms/signals/test/node/recursive_logic.spec.ts
  packages/forms/signals/test/node/resource.spec.ts
  packages/forms/signals/test/node/submit.spec.ts
  packages/forms/signals/test/node/validation_status.spec.ts
  packages/forms/signals/test/web/BUILD.bazel
  packages/forms/signals/test/web/control_directive.spec.ts
Labels: area: forms, target: feature, area: docs

#63340 fix(form): set select value after option renders
  packages/forms/signals/src/controls/control.ts
  packages/forms/signals/test/web/control_directive.spec.ts
Labels: area: forms, target: feature

#63389 refactor(forms): move addDefaultField out of public API
  goldens/public-api/forms/signals/index.api.md
  packages/forms/signals/src/api/async.ts
  packages/forms/signals/src/api/logic.ts
  packages/forms/signals/src/api/structure.ts
  packages/forms/signals/src/api/validation_errors.ts
  packages/forms/signals/src/api/validators/standard_schema.ts
  packages/forms/signals/src/field/validation.ts
Labels: area: forms, target: feature

#63422 Bump version to "v20.2.2" with changelog.
  CHANGELOG.md
  MODULE.bazel.lock
  package.json
Labels: action: merge, area: build & ci, PullApprove: disable

#63424 Bump version to "v21.0.0-next.1" with changelog.
  CHANGELOG.md
  MODULE.bazel.lock
  package.json
Labels: action: merge, area: build & ci, PullApprove: disable

#63471 Bump version to "v20.2.3" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, area: build & ci, PullApprove: disable

#63472 docs: release notes for the v20.2.3 release
  CHANGELOG.md
Labels: action: merge, area: build & ci, PullApprove: disable, area: docs
