Repository angular/angular, pull requests merged in 2025-04, with the labels that each got.

#60711 docs: release notes for the v19.2.5 release
  CHANGELOG.md
Labels: action: merge, PullApprove: disable, area: docs

#60712 Bump version to "v20.0.0-next.5" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, PullApprove: disable

#60813 docs: release notes for the v19.2.6 release
  CHANGELOG.md
Labels: action: merge, PullApprove: disable, area: docs

#60815 Bump version to "v20.0.0-next.6" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, PullApprove: disable

#60843 build: update post-approval dev-infra action
  .github/workflows/dev-infra.yml
Labels: action: merge, area: build & ci, target: minor

#60895 docs: release notes for the v19.2.7 release
  CHANGELOG.md
Labels: action: merge, PullApprove: disable, area: docs

#60791 refactor: use relative FieldPathNodes
  packages/forms/experimental/src/api/logic.ts
  packages/forms/experimental/src/api/structure.ts
  packages/forms/experimental/src/field_node.ts
  packages/forms/experimental/src/logic_node.ts
  packages/forms/experimental/src/path_node.ts
  packages/forms/experimental/src/schema.ts
  packages/forms/experimental/test/active_path.spec.ts
  packages/forms/experimental/test/api/when.spec.ts
  packages/forms/experimental/test/path.spec.ts
Labels: area: forms, forms: Signal

#60982 Bump version to "v19.2.8" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, PullApprove: disable

#60985 Bump version to "v19.2.8" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, PullApprove: disable

#60986 docs: release notes for the v19.2.8 release
  CHANGELOG.md
Labels: action: merge, area: build & ci, PullApprove: disable

#60987 Bump version to "v20.0.0-next.8" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, area: build & ci, PullApprove: disable

#61070 Bump version to "v19.2.9" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, PullApprove: disable

#61071 docs: release notes for the v19.2.9 release
  CHANGELOG.md
Labels: action: merge, PullApprove: disable, area: docs

#61072 Bump version to "v20.0.0-next.9" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, PullApprove: disable
