Repository angular/angular, pull requests merged in 2025-09, with the labels that each got.

#63574 Bump version to "v20.2.4" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, area: build & ci, PullApprove: disable

#63575 docs: release notes for the v20.2.4 release
  CHANGELOG.md
Labels: action: merge, area: build & ci, PullApprove: disable, area: docs

#63576 Bump version to "v21.0.0-next.2" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, area: build & ci, PullApprove: disable

#63639 fix(core): introduce `BootstrapContext` for improved server bootstrapping
  .aspect/rules/external_repository_action_cache/npm_translate_lock_MzA5NzUwNzMx
  .github/workflows/dev-infra.yml
  WORKSPACE
  adev/src/main.server.ts
  goldens/public-api/platform-browser/index.api.md
  goldens/public-api/platform-server/index.api.md
  integration/platform-server-hydration/src/main.server.ts
  integration/platform-server-zoneless/projects/standalone/src/main.server.ts
  integration/platform-server/projects/standalone/src/main.server.ts
  modules/ssr-benchmarks/src/main.server.ts
  packages/core/schematics/BUILD.bazel
  packages/core/schematics/migrations.json
  packages/core/schematics/migrations/add-bootstrap-context-to-server-main/BUILD.bazel
  packages/core/schematics/migrations/add-bootstrap-context-to-server-main/README.md
  packages/core/schematics/migrations/add-bootstrap-context-to-server-main/index.ts
  packages/core/schematics/migrations/add-bootstrap-context-to-server-main/migration.ts
  packages/core/schematics/test/add_bootstrap_context_to_server_main_spec.ts
  packages/core/src/application/create_application.ts
  packages/core/src/core_private_export.ts
  packages/core/src/platform/platform.ts
  packages/core/test/bundling/forms_reactive/bundle.golden_symbols.json
  packages/core/test/bundling/forms_template_driven/bundle.golden_symbols.json
  packages/platform-browser/src/browser.ts
  packages/platform-browser/src/platform-browser.ts
  packages/platform-server/src/server.ts
  packages/platform-server/src/utils.ts
  packages/platform-server/test/hydration_utils.ts
  packages/platform-server/test/integration_spec.ts
  pnpm-lock.yaml
  tools/npm-patches/@angular+ssr+19.2.0-next.2.patch
Labels: action: merge, target: lts, merge: caretaker note

#63689 docs: release notes for the v20.3.0-rc.0 release
  CHANGELOG.md
Labels: action: merge, area: build & ci, PullApprove: disable, area: docs

#63691 docs: release notes for the v20.3.0 release
  CHANGELOG.md
Labels: action: merge, area: build & ci, PullApprove: disable, area: docs

#63889 docs: release notes for the v20.3.1 release
  CHANGELOG.md
Labels: action: merge, area: build & ci, PullApprove: disable, area: docs

#63891 Bump version to "v21.0.0-next.4" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, area: build & ci, PullApprove: disable

#64067 docs: release notes for the v20.3.2 release
  CHANGELOG.md
Labels: action: merge, area: build & ci, PullApprove: disable, area: docs

#64068 Bump version to "v21.0.0-next.5" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, area: build & ci, PullApprove: disable
