Repository angular/angular, pull requests merged in 2025-03, with the labels that each got.

#60223 Bump version to "v19.2.1" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, PullApprove: disable

#60224 docs: release notes for the v19.2.1 release
  CHANGELOG.md
Labels: action: merge, PullApprove: disable, area: docs

#60225 Bump version to "v20.0.0-next.1" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, PullApprove: disable

#60351 Bump version to "v19.2.2" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, area: build & ci, PullApprove: disable

#60352 docs: release notes for the v19.2.2 release
  CHANGELOG.md
Labels: action: merge, PullApprove: disable, area: docs

#60353 Bump version to "v20.0.0-next.2" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, PullApprove: disable

#60469 Bump version to "v19.2.3" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, PullApprove: disable

#60470 docs: release notes for the v19.2.3 release
  CHANGELOG.md
Labels: action: merge, PullApprove: disable, area: docs

#60472 Bump version to "v20.0.0-next.3" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, PullApprove: disable

#60575 Bump version to "v19.2.4" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, area: build & ci, PullApprove: disable

#60576 docs: release notes for the v19.2.4 release
  CHANGELOG.md
Labels: action: merge, area: build & ci, PullApprove: disable

#60577 Bump version to "v20.0.0-next.4" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, PullApprove: disable
