Repository angular/angular, pull requests merged in 2025-01, with the labels that each got.

#59432 Bump version to "v19.0.6" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, PullApprove: disable

#59433 docs: release notes for the v19.0.6 release
  CHANGELOG.md
Labels: action: merge, PullApprove: disable, area: docs

#59434 Bump version to "v19.1.0-rc.0" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, PullApprove: disable

#59541 docs: release notes for the v19.0.7 release
  CHANGELOG.md
Labels: action: merge, PullApprove: disable, area: docs

#59542 Bump version to "v19.1.0" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, PullApprove: disable

#59564 Bump version to "v19.1.1" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, PullApprove: disable

#59565 docs: release notes for the v19.1.1 release
  CHANGELOG.md
Labels: action: merge, PullApprove: disable, area: docs

#59629 Bump version to "v19.1.2" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, PullApprove: disable

#59630 docs: release notes for the v19.1.2 release
  CHANGELOG.md
Labels: action: merge, PullApprove: disable, area: docs

#59671 Bump version to "v19.1.3" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, PullApprove: disable

#59672 docs: release notes for the v19.1.3 release
  CHANGELOG.md
Labels: action: merge, PullApprove: disable, area: docs

#59673 Bump version to "v19.2.0-next.0" with changelog.
  CHANGELOG.md
Labels: action: merge, PullApprove: disable

#59776 ci: update to latest version of dev-infra actions
  .github/actions/saucelabs-legacy/action.yml
  .github/workflows/adev-preview-build.yml
  .github/workflows/adev-preview-deploy.yml
  .github/workflows/assistant-to-the-branch-manager.yml
  .github/workflows/benchmark-compare.yml
  .github/workflows/ci.yml
  .github/workflows/dev-infra.yml
  .github/workflows/google-internal-tests.yml
  .github/workflows/manual.yml
  .github/workflows/merge-ready-status.yml
  .github/workflows/pr.yml
  .github/workflows/update-cli-help.yml
Labels: action: merge, area: build & ci, target: lts

#59794 Bump version to "v19.1.4" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, PullApprove: disable

#59795 docs: release notes for the v19.1.4 release
  CHANGELOG.md
Labels: action: merge, PullApprove: disable, area: docs

#59797 Bump version to "v19.2.0-next.1" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, PullApprove: disable
